packages:
  - apps/*
  - packages/*
allowBuilds:
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/windows-x64': true
  embedded-postgres: true
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: true
  ssh2: false
  sharp: true
