import EmbeddedPostgres from 'embedded-postgres';
import Fastify from 'fastify';
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createServer} from 'node:net';
import {connect,migrate,ensureGuild,sql,tenant} from '../../packages/db/src/index.js';
import {IdentityVault} from '../../packages/identity/src/index.js';
import {SettingsService} from '../../packages/settings/src/index.js';
import {AnalyticsService} from '../../packages/analytics/src/index.js';
import {ServerAuthorization} from '../../packages/security/src/server-authorization.js';
import {ServerVerification} from '../../packages/security/src/server-verification.js';
import {scopeForGuild} from '../../packages/security/src/scoping.js';
import {createApi} from '../../apps/api/src/server.js';
import {DiscordFailure} from '../../packages/discord/src/rest.js';
import {FakeDiscord} from '../fixtures/discord.js';
const port=Number(process.env.NEXUS_VERIFICATION_API_PORT??3151),user='911111111111111111',other='911111111111111112',manager='921111111111111111',admin='921111111111111112';
const ids=['931111111111111111','931111111111111112','931111111111111113','931111111111111114','931111111111111115'];
const installed=new Set([ids[0]!,ids[1]!,ids[2]!,ids[4]!]),names=['Verified community','Unverified community','Pending community','Add NEXUS community','Unauthorized community'];
await mkdir('.local',{recursive:true});const dir=await mkdtemp(resolve('.local/pg-verification-e2e-'));
const pgPort=await new Promise<number>(done=>{const probe=createServer();probe.listen(0,'127.0.0.1',()=>{const address=probe.address();if(!address||typeof address==='string')throw new Error('PORT_UNAVAILABLE');probe.close(()=>done(address.port));});});
const pg=new EmbeddedPostgres({databaseDir:dir,user:'nexus',password:'nexus',port:pgPort,persistent:true,onLog:()=>{},onError:()=>{}});await pg.initialise();await pg.start();
const databaseUrl=`postgresql://nexus:nexus@127.0.0.1:${pgPort}/postgres`,db=connect(databaseUrl);await migrate(db);
class VerificationDiscord extends FakeDiscord{async options(){return {channels:[],roles:[],events:[]};}}
const vault=new IdentityVault('aa'.repeat(32),'bb'.repeat(32)),settings=new SettingsService(db),discord=new VerificationDiscord(),permissions=new Map<string,boolean>();
discord.member=async(guildId,userId)=>{if(!installed.has(guildId))throw new DiscordFailure(404);const allowed=permissions.get(`${guildId}:${userId}`)??guildId!==ids[4];return {roles:allowed?[manager]:[],permissions:'0',bot:false,joinedAt:'2026-01-01T00:00:00.000Z'};};
const authority=new ServerAuthorization(discord,settings,vault),verification=new ServerVerification(db,vault,authority);
for(const guildId of installed){const s=scopeForGuild(guildId);await ensureGuild(db,s);await settings.update(s,{key:vault.hash(s,user),permissions:'32',roles:[],source:'DISCORD_PANEL',requestId:'fixture'},0,{uiLanguage:'en',managerRoleIds:[manager]});}
const verified=await verification.issue(scopeForGuild(ids[0]!),user);await verification.redeem(user,verified.code);await verification.issue(scopeForGuild(ids[2]!),user);
await writeFile('.local/verification-e2e.json',JSON.stringify({databaseUrl}),'utf8');
const api=createApi(new AnalyticsService(db,settings),'verification-api-key',db,discord);await api.listen({host:'127.0.0.1',port:port+2});
const fixture=Fastify({logger:false});fixture.get('/health',async()=>({ok:true}));
fixture.get('/fixture/discord/users/@me',async request=>({id:request.headers.authorization?.split('-').at(-1)??user}));
fixture.get('/fixture/discord/users/@me/guilds',async request=>request.headers.authorization?.startsWith('Bot ')?ids.filter(id=>installed.has(id)).map(id=>({id})):ids.map((id,index)=>({id,name:names[index],permissions:id===ids[3]?'32':'0'})));
fixture.get('/fixture/discord/guilds/:guildId',async(request,reply)=>{const {guildId}=request.params as {guildId:string};return installed.has(guildId)?{id:guildId,owner_id:'999111111111111111'}:reply.code(404).send({});});
fixture.get('/fixture/discord/guilds/:guildId/roles',async request=>{const {guildId}=request.params as {guildId:string};return [{id:guildId,permissions:'0',position:0,managed:false},{id:manager,permissions:'0',position:1,managed:false},{id:admin,permissions:'32',position:2,managed:false}];});
fixture.get('/fixture/discord/guilds/:guildId/members/:userId',async(request,reply)=>{const {guildId,userId}=request.params as {guildId:string;userId:string};try{const member=await discord.member(guildId,userId);return {roles:member.roles,joined_at:member.joinedAt,user:{bot:false}};}catch{return reply.code(404).send({});}});
fixture.post('/fixture/code',async request=>{const {guildId,userId=user}=request.body as {guildId:string;userId?:string};const s=scopeForGuild(guildId);await sql`UPDATE server_verification_challenges SET created_at=created_at-interval '31 seconds' WHERE ${tenant(s)} AND issuer_hash=${vault.hash(s,userId)}`.execute(db);const issued=await verification.issue(s,userId);return {code:issued.code};});
fixture.post('/fixture/permission',async request=>{const {guildId,userId=user,allowed}=request.body as {guildId:string;userId?:string;allowed:boolean};permissions.set(`${guildId}:${userId}`,allowed);return {ok:true};});
fixture.get('/fixture/data/:guildId',async request=>{const {guildId}=request.params as {guildId:string};return {settings:await settings.get(scopeForGuild(guildId)),connection:await verification.connection(scopeForGuild(guildId))};});
fixture.get('/fixture/constants',async()=>({ids,user,other}));
await fixture.listen({host:'127.0.0.1',port});
let stopping=false;const stop=async()=>{if(stopping)return;stopping=true;await fixture.close();await api.close();await db.destroy();await pg.stop();};process.on('SIGINT',()=>void stop());process.on('SIGTERM',()=>void stop());
