'use client';
import {useState} from 'react';
type Metric={metricKey:string,metricVersion:number,value:number|null,sampleSize:number,provisional:boolean,dataCoverage:{signal:string,status:string}};
type Revision={id:string,domain:string,version:number,definition:unknown,state:string,hash:string};
export type Dashboard={metrics:Record<string,Metric>,diagnoses:{type:string,confidenceLabel:string,causality:string}[],capability:Record<string,unknown>|null,revisions:Revision[],interventions:{id:string,state:string,reason:string|null}[],experiments:Record<string,unknown>[],usage:{plan:string,used:number,included:number|null,softLimit:number|null,projected:number},settings:Record<string,unknown>};
const pages=['Overview','Native Readiness','Lifecycle','Cohorts','Diagnoses','Interventions','Experiments','Reports','Data Health','Settings'];
const titles:Record<string,string>={new_members:'New Members',activation_rate:'Activation',d7_active_retention:'D7 Active Retention',ttfv_median:'Median TTFV',direct_reply_connection_rate:'Direct Reply Connection'};
const format=(key:string,m:Metric)=>m.value===null?'—':key.startsWith('ttfv')||key.includes('latency')?`${Math.round(m.value/60)} min`:key==='new_members'?m.value.toLocaleString():`${(m.value*100).toFixed(1)}%`;
export default function Console({data}:{data:Dashboard}){
 const [page,setPage]=useState('Overview'),[domain,setDomain]=useState('activation'),[event,setEvent]=useState('reply.received'),[channel,setChannel]=useState(''),[delay,setDelay]=useState(24),[safety,setSafety]=useState('suggest'),[treatment,setTreatment]=useState(''),[randomization,setRandomization]=useState('time_block');
 const [preview,setPreview]=useState<{before:{id:string}|null,after:Revision,confirmationHash:string}|null>(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const [advanced,setAdvanced]=useState(false),[policy,setPolicy]=useState('');
 async function request(body:unknown){setBusy(true);try{const response=await fetch('/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Request failed');return result;}catch(error){setStatus(error instanceof Error?error.message:'Request failed');return null;}finally{setBusy(false);}}
 async function draft(){
  const definition=domain==='activation'?{name:`${event} within 7d`,windowSeconds:604800,rule:{op:'event',event,withinSeconds:604800}}:domain==='intervention'?{name:'Newcomer helper alert',trigger:'member.joined',delaySeconds:delay*3600,conditions:[],actions:[{type:'staff_alert',channelId:channel,text:'A newcomer may need help getting started.'}],cooldownSeconds:604800,safetyMode:safety,frequencyCaps:{dmPerDay:1,contactsPerWeek:3},massRoleOperation:false}:{name:'Helper alert vs holdout',eligibility:[],randomization,blockSeconds:86400,variants:[{key:'control',weight:50,interventionRevisionId:null},{key:'treatment',weight:50,interventionRevisionId:treatment}],primaryMetric:'activation',windowSeconds:604800,minimumSample:20,guardrails:{maxLeaveRate:.3,maxFailureRate:.1,maxAlerts:100}};
  let value:unknown=definition;
  if(advanced){try{value=JSON.parse(policy);}catch{setStatus('Enter a valid typed policy JSON object.');return;}}
  const result=await request({action:'draft',domain,definition:value});if(result){setPreview(result);setStatus('Draft validated. Review before publishing.');}
 }
 async function publish(){if(!preview)return;const result=await request({action:'publish',id:preview.after.id,expectedHead:preview.before?.id??null,confirmationHash:preview.confirmationHash});if(result){setPreview(null);setStatus('Published. Reload to see the latest state.');}}
 const metricCards=(keys:string[])=><section className="metrics">{keys.flatMap(key=>{const m=data.metrics[key];return m?[<article key={key}><h2>{titles[key]??key.replaceAll('_',' ')}</h2><div className="value">{format(key,m)}</div><footer><span>n = {m.sampleSize} · v{m.metricVersion}{m.provisional?' · provisional':''}</span><span className={m.dataCoverage.status==='healthy'?'complete':'partial'}>{m.dataCoverage.status}</span></footer></article>]:[];})}</section>;
 const findings=<section className="notice"><h2>Needs Attention</h2>{data.diagnoses.length?data.diagnoses.map((d,i)=><p key={i}>{d.type} · {d.confidenceLabel}<br/>Causality: not established</p>):<p>No diagnosis meets the evidence threshold.</p>}</section>;
 const builder=<section className="builder"><h2>{domain==='activation'?'Activation Builder':domain==='intervention'?'Intervention Studio':'Experiment Builder'}</h2>
 <label>Definition<select value={domain} onChange={e=>{setDomain(e.target.value);setPreview(null);}}><option value="activation">Activation</option><option value="intervention">Intervention</option><option value="experiment">Experiment</option></select></label>
 {domain==='activation'?<label>First-value signal within 7 days<select value={event} onChange={e=>setEvent(e.target.value)}><option value="reply.received">Receive a direct reply</option><option value="scheduled_event.subscribed">Subscribe to an event</option><option value="message.sent">Send a message</option></select></label>:domain==='intervention'?<><label>Staff channel ID<input value={channel} onChange={e=>setChannel(e.target.value)} inputMode="numeric"/></label><p>Discord’s Interventions panel offers a channel picker.</p><label>Hours after join<input type="number" min="0" max="168" value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label><label>Safety<select value={safety} onChange={e=>setSafety(e.target.value)}><option value="suggest">Suggest</option><option value="approval">Approval</option><option value="auto">Auto</option></select></label></>:<><label>Treatment intervention<select value={treatment} onChange={e=>setTreatment(e.target.value)}><option value="">Choose published intervention</option>{data.revisions.filter(r=>r.domain==='intervention'&&r.state==='published').map(r=><option key={r.id} value={r.id}>Intervention v{r.version}</option>)}</select></label><label>Randomization<select value={randomization} onChange={e=>setRandomization(e.target.value)}><option value="time_block">Daily time blocks</option><option value="member">Member</option></select></label><p>Control: no action. Treatment: published intervention. Staff alerts can affect other members; time blocks are recommended. Evidence requires at least 20 mature blocks per arm; cross-block spillover remains a limitation.</p></>}
 <label><span><input type="checkbox" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/> Advanced typed policy</span></label>
 {advanced&&<label>Policy JSON<textarea rows={12} value={policy} onChange={e=>setPolicy(e.target.value)} placeholder={'{"name":"Voice first value","windowSeconds":604800,"rule":{"op":"duration","event":"voice.duration","gteSeconds":300,"withinSeconds":604800}}'}/><small>Only the typed policy schema is accepted. No JavaScript, SQL or executable expressions. Activation supports all / any / not, event, count, duration, roles, channels, replies and flow answers.</small></label>}
 <button disabled={busy} onClick={draft}>Validate and preview</button>
 {preview&&<section className="notice"><h3>Publish version {preview.after.version}</h3><pre>{JSON.stringify(preview.after.definition,null,2)}</pre><button disabled={busy} onClick={publish}>Confirm publication</button></section>}
 </section>;
 return <div className="workspace"><nav aria-label="NEXUS navigation">{pages.map(p=><button key={p} aria-current={page===p?'page':undefined} onClick={()=>setPage(p)}>{p}</button>)}</nav><div className="workspace-content"><h1 className="page-title">{page}</h1>
 {Object.values(data.metrics).some(m=>m.dataCoverage.status!=='healthy')&&<section className="notice" role="status"><strong>Coverage needs attention</strong><p>Unavailable observations are shown as —. Provisional cohorts have not finished their observation window.</p></section>}
 {page==='Overview'&&<>{metricCards(Object.keys(titles))}<section className="notice"><h2>Lifecycle Funnel</h2><p>Join → Native / Fallback → Home Actions → First Value → Activated → Active Retention</p><p>Stages are observable milestones; members may skip stages. Completion rates use their defined windows.</p></section>{findings}<section className="notice"><h2>Experiments</h2><p>{data.experiments.length} published experiments · Intention-to-treat analysis</p><button onClick={()=>setPage('Experiments')}>Review experiments</button></section></>}
 {page==='Native Readiness'&&<section className="notice"><h2>Discord Native</h2>{data.capability?<dl>{['communityEnabled','nativeOnboardingAvailable','nativeOnboardingEnabled','membershipScreeningEnabled','recommendedMode','checkedAt'].map(key=><div key={key}><dt>{key}</dt><dd>{String(data.capability![key]??'Unavailable')}</dd></div>)}</dl>:<p>Run /nexus setup in Discord to read current capabilities.</p>}<p>Native answers, channel views and DM reads are not observable.</p></section>}
 {page==='Lifecycle'&&<>{metricCards(Object.keys(data.metrics))}{builder}</>}
 {page==='Diagnoses'&&findings}
 {page==='Interventions'&&<>{builder}<h2>Delivery and approvals</h2>{data.interventions.map(r=><section className="notice" key={r.id}><p>{r.state} {r.reason??''}</p>{['suggested','approval'].includes(r.state)&&<button disabled={busy} onClick={async()=>{if(await request({action:'approve',id:r.id}))setStatus('Approved; safety is rechecked before delivery.');}}>Approve intervention</button>}</section>)}</>}
 {page==='Experiments'&&<>{builder}{data.experiments.map((e,i)=><section key={i} className="notice"><h2>Experiment result</h2><pre>{JSON.stringify(e,null,2)}</pre>{['paused','stopped'].map(state=><button key={state} disabled={busy||e.state==='stopped'} onClick={async()=>{if(await request({action:'experiment_control',id:e.id,state}))setStatus(`Experiment ${state}. Reload for latest status.`);}}>{state==='paused'?'Pause experiment':'Stop experiment'}</button>)}</section>)}</>}
 {page==='Data Health'&&<section className="notice"><h2>Input coverage</h2>{Object.values(data.metrics).map(m=><p key={m.metricKey}>{m.metricKey}: {m.dataCoverage.status}</p>)}</section>}
 {page==='Settings'&&<><section className="notice"><h2>Plan and Monthly Tracked Members</h2><p>{data.usage.plan} · {data.usage.used} / {data.usage.included??'Custom'} MTM</p><p>Soft limit {data.usage.softLimit??'Custom'} · Projected {data.usage.projected}. No automatic overage charges.</p><h2>Discord / Onboarding / Privacy</h2><p>Use /nexus setup and Advanced in Discord to configure Native/Fallback/Hybrid and existing flows. Member deletion is available through /nexus privacy.</p><p>Detailed retention: {String(data.settings.detailedRetentionDays)} days. Aggregate retention: {String(data.settings.aggregateRetentionMonths)} months.</p><h2>Team</h2><p>Administration uses Manage Guild or the configured NEXUS admin role. The web console uses the configured guild administration password.</p></section>{builder}<h2>Configuration history</h2>{data.revisions.filter(r=>r.state==='published').map(r=><p key={r.id}>{r.domain} v{r.version} <button disabled={busy} onClick={async()=>{const p=await request({action:'rollback',id:r.id});if(p){setPreview(p);setStatus('Rollback draft ready. Review before publication.');}}}>Preview rollback</button></p>)}</>}
 {page==='Cohorts'&&<section className="notice"><p>Current metrics use join-date membership cohorts. Advanced cohort editing is not enabled.</p></section>}
 {page==='Reports'&&<section className="notice"><p>Scheduled reports are planned for P1. Current metrics are available in Overview and Lifecycle.</p></section>}
 <p role="status">{status}</p></div></div>;
}

