import type {CommunityService} from '../../../packages/presentation/src/community';
import {activityWindow,replyDenominator,measurementLabel} from '../../../packages/discord-panels/src/i18n/terminology';
import {t} from '../../../packages/discord-panels/src/i18n/index';
type Community=Awaited<ReturnType<CommunityService['overview']>>;
export function Measurements({community,locale}:{community:Community;locale:'ja'|'en'}){
 const date=(value:string)=>new Date(value).toLocaleDateString(locale==='ja'?'ja-JP':'en-US',{timeZone:community.daily.timezone});
 return <section className="surface"><h2>{t(locale,'polish.week')}</h2><p>{t(locale,'polish.weekIntro')}</p><div className="kpi-grid measurement-grid">{(['reply','connection','retention'] as const).map(key=>{const metric=community.weekly[key],delta=metric.value===null||metric.previous===null?null:metric.value-metric.previous;return <article className="metric-card" key={key}><h3>{key==='retention'?activityWindow(locale,metric.activityFromDay,metric.observationDays):t(locale,key==='reply'?'polish.replyTime':'polish.connection')}</h3><strong className={metric.value===null?"measurement-state":""}>{measurementLabel(metric,locale,key==='reply')}</strong><p>{key==='reply'?replyDenominator(locale,metric):metric.value!==null?`${metric.numerator} / ${metric.sample} ${locale==='ja'?'人':'members'}`:''}</p><small>{t(locale,'polish.period',{from:date(metric.from),through:date(new Date(new Date(metric.through).getTime()-1).toISOString()),days:metric.observationDays})}</small>{delta!==null&&<p>{delta===0?t(locale,'polish.same'):key==='reply'?t(locale,delta<0?'polish.faster':'polish.slower',{count:Math.abs(delta)}):t(locale,'polish.points',{count:`${delta>0?'+':''}${delta}`})}</p>}</article>})}</div></section>;
}
export function AnalysisSummary({community,locale}:{community:Community;locale:'ja'|'en'}){
 const analysis=community.analysis,metric=analysis.retention;
 return <section className="surface"><h1>{t(locale,'control.newMembers')}</h1><p>{t(locale,'control.days',{count:community.range})}</p>{metric.value===null&&<p>{measurementLabel(metric,locale)}</p>}<div className="kpi-grid measurement-grid"><article className="metric-card"><h2>{t(locale,'control.joined')}</h2><strong>{analysis.joined===null?t(locale,'polish.unavailable'):t(locale,'polish.people',{count:analysis.joined})}</strong></article><article className="metric-card"><h2>{activityWindow(locale,analysis.rules.retainedFromDay,analysis.rules.retainedThroughDay)}</h2><strong className={metric.value===null?"measurement-state":""}>{measurementLabel(metric,locale)}</strong><p>{metric.value!==null?`${metric.numerator} / ${metric.sample}`:''}</p><small>{new Date(metric.from).toLocaleDateString(locale,{timeZone:community.daily.timezone})}〜{new Date(new Date(metric.through).getTime()-1).toLocaleDateString(locale,{timeZone:community.daily.timezone})}</small></article><article className="metric-card"><h2>{t(locale,'control.exited')}</h2><strong>{analysis.exited===null?t(locale,'polish.unavailable'):t(locale,'polish.people',{count:analysis.exited})}</strong></article></div>{metric.value!==null&&metric.previous!==null&&<p>{t(locale,'polish.points',{count:`${metric.value-metric.previous>0?'+':''}${metric.value-metric.previous}`})} ({metric.previous}% → {metric.value}%)</p>}<details><summary>{t(locale,'polish.rules')}</summary><p>{t(locale,'control.staffExcluded')}: {community.classification.staffExcluded}</p><p>{locale==='ja'?`参加後${analysis.rules.startingDays}日を過ぎたメンバーを、過去${analysis.rules.recentDays}日間の活動日数（${analysis.rules.activeDays}日以上・未満）で分けます。`:`Members past ${analysis.rules.startingDays} days are grouped by whether they had at least ${analysis.rules.activeDays} active days in the past ${analysis.rules.recentDays} days.`}</p><p>{t(locale,'control.observation')}</p></details></section>;
}
