import {Preview,SiteCta,SiteShell,copy,siteLocale} from './public-ui';
export default async function Home(){const locale=await siteLocale();return <SiteShell locale={locale}>
 <section className="site-hero"><div className="hero-copy"><p className="site-eyebrow">DISCORD COMMUNITY OPERATIONS</p><h1>{copy(locale,<>新しいメンバーが<br/><em>「入っただけ」</em>で<br/>終わらないコミュニティへ。</>,<>Help every newcomer<br/>find their <em>first connection.</em></>)}</h1><p className="site-lead">{copy(locale,'NEXUSは参加から最初の交流、返信、継続までを見て、運営が今できることを示すDiscord向けのコミュニティ運営アシスタントです。','NEXUS follows the path from joining to first replies and returning activity, then shows community teams what they can do next.')}</p><SiteCta locale={locale}/><p className="hero-note">{copy(locale,'ログインは管理画面へ · Botの追加はDiscordの認可画面へ','Sign in opens the dashboard · Add to Discord starts bot installation')}</p></div><div className="hero-visual"><Preview locale={locale}/></div></section>
 <section className="site-section story-intro"><p className="site-eyebrow">THE PROBLEM</p><h2>{copy(locale,<>参加者は増えている。<br/>でも、馴染めているかは分からない。</>,<>People join. But are they finding their place?</>)}</h2><p>{copy(locale,'参加人数だけでは、最初の投稿が返信されたか、誰かと交流できたかは見えません。NEXUSは運営が動ける形でその差を示します。','A join count cannot tell you whether a first post received a reply or a member connected with someone. NEXUS turns those gaps into clear next steps.')}</p></section>
 <section className="site-section"><div className="section-heading"><p className="site-eyebrow">HOW NEXUS WORKS</p><h2>{copy(locale,'見る。その理由を知る。改善する。','From signal to action, in one flow.')}</h2></div><div className="story-grid">{[copy(locale,['01','見る','新規メンバーの参加と最初の交流を確認。'],['01','Observe','See newcomer activity and first connections.']),copy(locale,['02','気づく','返信待ちや交流の止まりを見つける。'],['02','Detect','Spot unanswered posts and stalled paths.']),copy(locale,['03','理由を知る','人数・期間・判定条件を示す。'],['03','Explain','Show the evidence, sample, and measurement rule.']),copy(locale,['04','実行する','Discord上で対応し、変更前にプレビュー。'],['04','Act','Respond in Discord and preview changes.']),copy(locale,['05','効果を見る','改善後の変化を、データが揃ってから確認。'],['05','Measure','Compare outcomes when enough data has matured.'])].map(([number,title,body])=><article className="story-card" key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="site-section split-feature"><div><p className="site-eyebrow">DISCORD + WEB</p><h2>{copy(locale,'今日の対応はDiscordで。長期の改善はWebで。','Respond in Discord. Understand the pattern on Web.')}</h2><p>{copy(locale,'対応キューでは投稿を開き、スタッフ確認、後で確認、解決を選べます。Webでは新規メンバーの流れ、根拠、改善結果をたどれます。','Open a post, acknowledge it, snooze it, or resolve it from Discord. Use Web to follow the newcomer journey, evidence, and results.')}</p><a className="inline-link" href="/product">{copy(locale,'使い方を見る','See how it works')} →</a></div><div className="feature-panel"><span className="badge badge-amber">{copy(locale,'対応','ATTENTION')}</span><h3>{copy(locale,'返信を待っている投稿','A post is waiting for a reply')}</h3><p>#general · 37 min</p><div className="mock-buttons"><span>{copy(locale,'投稿を開く','Open post')}</span><span>{copy(locale,'スタッフ確認','Acknowledge')}</span><span>{copy(locale,'後で','Snooze')}</span></div><small>{copy(locale,'画面イメージ · サンプルデータ','Illustrative preview · Example data')}</small></div></section>
 <section className="site-section trust-strip"><div><p className="site-eyebrow">MEASUREMENT YOU CAN INSPECT</p><h2>{copy(locale,'数字の意味を、隠さない。','Know what every number means.')}</h2><p>{copy(locale,'「最初の交流」は直接返信やボイスでの交流を確認したもの。イベントの参加登録を実際の参加とは呼びません。観測が足りないときは0ではなく「測定中」と表示します。','A first connection requires an observable interaction, such as a direct reply or voice connection. Event signup is never labeled attendance. Missing data appears as collecting, not zero.')}</p></div><div className="rule-preview"><span className="badge badge-violet">{copy(locale,'判定ルール','MEASUREMENT RULE')}</span><h3>💬 {copy(locale,'最初の投稿に返信がつく','First post receives a reply')}</h3><dl><div><dt>{copy(locale,'対象','Who')}</dt><dd>{copy(locale,'新規メンバー','New members')}</dd></div><div><dt>{copy(locale,'判定','Detected by')}</dt><dd>{copy(locale,'別のメンバーからの直接返信','Direct reply from another member')}</dd></div><div><dt>{copy(locale,'除外','Excluded')}</dt><dd>Bots · {copy(locale,'本人','Self replies')}</dd></div></dl></div></section>
 <section className="site-section final-cta"><p className="site-eyebrow">START WITH THE FIRST CONNECTION</p><h2>{copy(locale,'次の「はじめまして」を、見逃さない。','Make the next first hello count.')}</h2><SiteCta locale={locale}/></section>
 </SiteShell>}
