import {cookies,headers} from 'next/headers';
import type {ReactNode} from 'react';
import {installUrl} from './auth/session';

export type SiteLocale='ja'|'en';
export async function siteLocale():Promise<SiteLocale>{
 const saved=(await cookies()).get('nexus_locale')?.value;
 if(saved==='ja'||saved==='en')return saved;
 return (await headers()).get('accept-language')?.toLowerCase().startsWith('ja')?'ja':'en';
}
export const copy=<T,>(locale:SiteLocale,ja:T,en:T):T=>locale==='ja'?ja:en;

export function SiteHeader({locale}:{locale:SiteLocale}){
 const add=installUrl();
 return <header className="site-header"><div className="site-header-inner"><a className="site-logo" href="/" aria-label="NEXUS home"><span className="site-logo-mark">✦</span>NEXUS</a><nav aria-label="Main navigation"><a href="/product">{copy(locale,'製品','Product')}</a><a href="/pricing">{copy(locale,'料金','Pricing')}</a><a href="/support">{copy(locale,'サポート','Support')}</a></nav><div className="site-actions"><a className="text-link" href="/auth/login">{copy(locale,'ログイン','Log in')}</a>{add&&<a className="button button-discord" href={add}>{copy(locale,'Discordに追加','Add to Discord')}</a>}<details className="language-menu"><summary aria-label="Language">{locale.toUpperCase()}</summary><form action="/locale" method="post"><button name="locale" value="ja">日本語</button><button name="locale" value="en">English</button></form></details></div><details className="mobile-site-menu"><summary aria-label={copy(locale,'メニュー','Menu')}>☰</summary><nav aria-label={copy(locale,'モバイルナビゲーション','Mobile navigation')}><a href="/product">{copy(locale,'製品','Product')}</a><a href="/pricing">{copy(locale,'料金','Pricing')}</a><a href="/support">{copy(locale,'サポート','Support')}</a><hr/><a href="/auth/login">{copy(locale,'ログイン','Log in')}</a>{add&&<a className="button button-discord" href={add}>{copy(locale,'Discordに追加','Add NEXUS to Discord')}</a>}<form action="/locale" method="post" aria-label={copy(locale,'言語','Language')}><button name="locale" value="ja">日本語</button><button name="locale" value="en">English</button></form></nav></details></div></header>;
}
export function SiteFooter({locale}:{locale:SiteLocale}){return <footer className="site-footer"><div><a className="site-logo" href="/"><span className="site-logo-mark">✦</span>NEXUS</a><p>{copy(locale,'新しいメンバーの最初の交流を、運営の力に。','Help newcomers find their first connection.')}</p></div><nav aria-label="Footer"><a href="/product">{copy(locale,'製品','Product')}</a><a href="/pricing">{copy(locale,'料金','Pricing')}</a><a href="/support">{copy(locale,'サポート','Support')}</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav></footer>}
export function SiteShell({locale,children}:{locale:SiteLocale;children:ReactNode}){return <div className="site"><SiteHeader locale={locale}/><main>{children}</main><SiteFooter locale={locale}/></div>}
export function SiteCta({locale,secondary=true}:{locale:SiteLocale;secondary?:boolean}){const add=installUrl();return <div className="cta-row">{add?<a className="button button-discord" href={add}>{copy(locale,'Discordに追加','Add NEXUS to Discord')} <span aria-hidden="true">↗</span></a>:<a className="button button-primary" href="/support">{copy(locale,'導入について問い合わせる','Ask about installation')}</a>}{secondary&&<a className="button button-secondary" href="/product">{copy(locale,'製品を見る','Explore the product')}</a>}</div>}
export function Preview({locale}:{locale:SiteLocale}){return <div className="site-preview" aria-label={copy(locale,'製品画面の説明用プレビュー','Illustrative product preview')}><div className="preview-bar"><span className="preview-dots">● ● ●</span><strong>✦ NEXUS</strong><span>{copy(locale,'画面イメージ · サンプルデータ','Illustrative preview · Example data')}</span></div><div className="preview-body"><div className="preview-side"><strong>NEXUS</strong><span>▦ {copy(locale,'概要','Overview')}</span><span>◉ {copy(locale,'新規メンバー','New Members')}</span><span>⌁ {copy(locale,'対応','Attention')}</span><span>◎ {copy(locale,'分析','Insights')}</span></div><div className="preview-main"><small>{copy(locale,'コミュニティの今','COMMUNITY TODAY')}</small><h3>{copy(locale,'最初の交流が生まれる場所を、見つける。','See where first connections begin.')}</h3><div className="preview-metrics"><div><span>{copy(locale,'新規参加','New members')}</span><strong>38</strong></div><div><span>{copy(locale,'最初の交流','First connection')}</span><strong>74%</strong></div><div><span>{copy(locale,'初回返信','First reply')}</span><strong>18 min</strong></div></div><div className="preview-insight"><span className="badge badge-violet">NEXUS INSIGHT</span><strong>{copy(locale,'返信が遅い場所が見つかりました','A slower reply path appeared')}</strong><p>{copy(locale,'#looking-for-group の初回返信はサーバー平均より14分遅れています。','First replies in #looking-for-group take 14 minutes longer than the server average.')}</p><small>{copy(locale,'17件の投稿を観測 · 例示データ','17 observed posts · Example data')}</small></div></div></div></div>}
