-- Capability revision 3 is additive. Historical revisions and purchased
-- commercial identities remain immutable; current plan benefits use the latest
-- capability registry. Existing alpha.7 Stripe Price/Offering revision 2 mappings
-- are intentionally retained because the recurring financial identity is unchanged.
INSERT INTO billing_plan_versions(plan_key,revision,features,limits) VALUES
('FREE',3,'["core_observation","basic_attention","connection_metrics","thread_forum_metrics","reaction_poll_metrics","voice_metrics","event_metrics","coverage_health","fallback_onboarding","hybrid_onboarding","interventions","discord_charts","intake_panels"]'::jsonb,'{"guilds":1,"historyDays":30,"monthlyObservedMembers":250,"customRecipes":0,"automationRules":0,"scheduledReports":0,"teamSeats":1,"webhooks":0,"apiRequestsMonthly":0,"intakePanels":1}'::jsonb),
('STARTER',3,'["core_observation","basic_attention","connection_metrics","thread_forum_metrics","reaction_poll_metrics","voice_metrics","event_metrics","coverage_health","fallback_onboarding","hybrid_onboarding","interventions","discord_charts","intake_panels","all_recipe_presets","surface_breakdowns","percentile_metrics","advanced_journeys","comparable_periods","scheduled_digest","basic_improvement_tracking","custom_activation","saved_views","heatmaps","csv_export","event_operations","advanced_cohorts","diagnosis","advanced_filters","drilldowns","saved_segments"]'::jsonb,'{"guilds":1,"historyDays":90,"monthlyObservedMembers":1000,"customRecipes":0,"automationRules":0,"scheduledReports":1,"teamSeats":1,"webhooks":0,"apiRequestsMonthly":0,"intakePanels":5}'::jsonb),
('GROWTH',3,'["core_observation","basic_attention","connection_metrics","thread_forum_metrics","reaction_poll_metrics","voice_metrics","event_metrics","coverage_health","fallback_onboarding","hybrid_onboarding","interventions","discord_charts","intake_panels","all_recipe_presets","surface_breakdowns","percentile_metrics","advanced_journeys","comparable_periods","scheduled_digest","basic_improvement_tracking","custom_activation","saved_views","heatmaps","csv_export","event_operations","custom_recipe","attention_automation","attention_escalation","improvement_tracking","scheduled_reports","team_routing","webhooks","ai_explanation","api","attention_inbox","playbooks","report_branding","advanced_cohorts","diagnosis","automation_auto","experiments","advanced_filters","drilldowns","saved_segments"]'::jsonb,'{"guilds":1,"historyDays":365,"monthlyObservedMembers":5000,"customRecipes":5,"automationRules":10,"scheduledReports":10,"teamSeats":5,"webhooks":5,"apiRequestsMonthly":10000,"intakePanels":25}'::jsonb),
('SCALE',3,'["core_observation","basic_attention","connection_metrics","thread_forum_metrics","reaction_poll_metrics","voice_metrics","event_metrics","coverage_health","fallback_onboarding","hybrid_onboarding","interventions","discord_charts","intake_panels","all_recipe_presets","surface_breakdowns","percentile_metrics","advanced_journeys","comparable_periods","scheduled_digest","basic_improvement_tracking","custom_activation","saved_views","heatmaps","csv_export","event_operations","custom_recipe","attention_automation","attention_escalation","improvement_tracking","scheduled_reports","team_routing","webhooks","ai_explanation","api","attention_inbox","playbooks","report_branding","multi_guild","rbac","audit_export","team_assignment","approval_workflow","automation_sandbox","recurring_exports","advanced_api","advanced_cohorts","diagnosis","automation_auto","experiments","advanced_filters","drilldowns","saved_segments"]'::jsonb,'{"guilds":5,"historyDays":730,"monthlyObservedMembers":25000,"customRecipes":25,"automationRules":50,"scheduledReports":50,"teamSeats":20,"webhooks":20,"apiRequestsMonthly":100000,"intakePanels":100}'::jsonb),
('ENTERPRISE',3,'["core_observation","basic_attention","connection_metrics","thread_forum_metrics","reaction_poll_metrics","voice_metrics","event_metrics","coverage_health","fallback_onboarding","hybrid_onboarding","interventions","discord_charts","intake_panels","all_recipe_presets","surface_breakdowns","percentile_metrics","advanced_journeys","comparable_periods","scheduled_digest","basic_improvement_tracking","custom_activation","saved_views","heatmaps","csv_export","event_operations","custom_recipe","attention_automation","attention_escalation","improvement_tracking","scheduled_reports","team_routing","webhooks","ai_explanation","api","attention_inbox","playbooks","report_branding","multi_guild","rbac","audit_export","team_assignment","approval_workflow","automation_sandbox","recurring_exports","advanced_api","advanced_cohorts","diagnosis","automation_auto","experiments","advanced_filters","drilldowns","saved_segments"]'::jsonb,'{"guilds":null,"historyDays":null,"monthlyObservedMembers":null,"customRecipes":null,"automationRules":null,"scheduledReports":null,"teamSeats":null,"webhooks":null,"apiRequestsMonthly":null,"intakePanels":null}'::jsonb);
