import {beforeAll,afterAll,it,expect} from "vitest";
import {connect,migrate,sql,json,type Database} from "../../packages/db/src/index";
import {infrastructure} from "../fixtures/infrastructure";
import {analysisFixture} from "../fixtures/analysis";
import {SetupWizard} from "../../packages/operations/src/setup-wizard";
import {buildCapabilitySnapshot} from "../../packages/discord/src/discovery";
import {representativeSource} from "../fixtures/community-profiles";
let infra:Awaited<ReturnType<typeof infrastructure>>,db:Database;
beforeAll(async()=>{infra=await infrastructure();db=connect(infra.databaseUrl);await migrate(db);});
afterAll(async()=>{await db?.destroy();await infra?.stop();});
it("snapshots 130 category children, pages/batches purpose settings, and never restores explicit exclusions or includes future channels",async()=>{
 const f=await analysisFixture(db),wizard=new SetupWizard(db),category="888888888888888888";
 const ids=Array.from({length:130},(_,i)=>String(777777777777777770n+BigInt(i)));
 const source=representativeSource(0);source.channels.push({id:category,type:4,parentId:null,observable:true,tagIds:[]},...ids.map(id=>({id,type:0,parentId:category,observable:true,tagIds:[]})));
 const snapshot=buildCapabilitySnapshot(source,new Date());
 await sql`UPDATE guild_capability_snapshots SET snapshot=${json(snapshot)},checked_at=now() WHERE organization_id=${f.s.organizationId}::uuid AND guild_id=${f.s.guildId}`.execute(db);
 let state=await wizard.open(f.s,f.actor);
 state=await wizard.change(f.s,f.actor,state.id,state.version,"mode",["include"]);
 state=await wizard.change(f.s,f.actor,state.id,state.version,"category",[category]);
 expect(state.draft.analysisScope.channelIds).toHaveLength(130);
 state=await wizard.change(f.s,f.actor,state.id,state.version,"removeChannels",[ids[0]!]);
 state=await wizard.change(f.s,f.actor,state.id,state.version,"category",[category]);
 expect(state.draft.analysisScope.channelIds).toHaveLength(129);
 expect(state.draft.analysisScope.excludedChannelIds).toEqual([ids[0]]);
 state=await wizard.change(f.s,f.actor,state.id,state.version,"purpose",["SHOWCASE"]);
 state=await wizard.change(f.s,f.actor,state.id,state.version,"channels",[f.channel]);
 state=await wizard.change(f.s,f.actor,state.id,state.version,"purpose",["SUPPORT"]);
 expect(state.draft.communityModel!.channels.filter(c=>c.purpose==="SHOWCASE")).toHaveLength(129);
 expect((await f.settings.get(f.s)).communityModel.channels).toHaveLength(1);
 state=await wizard.move(f.s,f.actor,state.id,state.version,"next");
 for(let step=1;step<4;step++)state=await wizard.move(f.s,f.actor,state.id,state.version,"skip");
 const saved=await wizard.confirm(f.s,f.actor,state.id,state.version);
 expect(saved.analysisScope.channelIds).toHaveLength(130);
 expect(saved.communityModel.channels.filter(c=>c.purpose==="SHOWCASE")).toHaveLength(129);
 expect(saved.communityModel.confirmed).toBe(true);
 const future="799999999999999999";
 source.channels.push({id:future,type:0,parentId:category,observable:true,tagIds:[]});
 await sql`UPDATE guild_capability_snapshots SET snapshot=${json(buildCapabilitySnapshot(source,new Date()))} WHERE organization_id=${f.s.organizationId}::uuid AND guild_id=${f.s.guildId}`.execute(db);
 expect((await f.settings.get(f.s)).analysisScope.channelIds).not.toContain(future);
});
it("restores saved values when a changed optional step is skipped and rejects missing scope channels at confirmation",async()=>{
 const f=await analysisFixture(db),wizard=new SetupWizard(db);
 let state=await wizard.open(f.s,f.actor);
 state=await wizard.move(f.s,f.actor,state.id,state.version,"next");
 state=await wizard.move(f.s,f.actor,state.id,state.version,"skip");
 state=await wizard.change(f.s,f.actor,state.id,state.version,"team",["888888888888888888"]);
 state=await wizard.move(f.s,f.actor,state.id,state.version,"skip");
 expect(state.draft.managerRoleIds).toEqual([]);
 state=await wizard.move(f.s,f.actor,state.id,state.version,"skip");
 expect((await wizard.confirm(f.s,f.actor,state.id,state.version)).managerRoleIds).toEqual([]);
 let invalid=await wizard.open(f.s,f.actor);
 invalid=await wizard.change(f.s,f.actor,invalid.id,invalid.version,"mode",["include"]);
 invalid=await wizard.change(f.s,f.actor,invalid.id,invalid.version,"channels",[f.channel]);
 invalid=await wizard.move(f.s,f.actor,invalid.id,invalid.version,"next");
 for(let step=1;step<4;step++)invalid=await wizard.move(f.s,f.actor,invalid.id,invalid.version,"skip");
 await sql`UPDATE guild_capability_snapshots SET snapshot=jsonb_set(snapshot,'{channels}','[]'::jsonb) WHERE organization_id=${f.s.organizationId}::uuid AND guild_id=${f.s.guildId}`.execute(db);
 const revision=(await f.settings.get(f.s)).revision;
 await expect(wizard.confirm(f.s,f.actor,invalid.id,invalid.version)).rejects.toThrow("CHANNEL_PERMISSION_MISSING");
 expect((await f.settings.get(f.s)).revision).toBe(revision);
});
