import {beforeAll,afterAll,it,expect} from 'vitest';
import {Redis} from 'ioredis';
import {randomUUID,generateKeyPairSync,sign} from 'node:crypto';
import {infrastructure} from '../fixtures/infrastructure.js';
import {connect,migrate,ensureGuild,sql,type Database} from '../../packages/db/src/index.js';
import {IdentityVault} from '../../packages/identity/src/index.js';
import {SettingsService} from '../../packages/settings/src/index.js';
import {OnboardingService} from '../../packages/onboarding/src/index.js';
import {LifecycleService} from '../../packages/lifecycle/src/index.js';
import {AnalyticsService} from '../../packages/analytics/src/index.js';
import {scopeForGuild,Components,apiToken} from '../../packages/security/src/index.js';
import {normalize,type Envelope} from '../../packages/events/src/index.js';
import {GatewayPublisher,STREAM} from '../../apps/gateway/src/index.js';
import {StreamConsumer} from '../../apps/worker/src/streams.js';
import {FakeDiscord} from '../fixtures/discord.js';
import {createInteractionServer} from '../../apps/interaction/src/server.js';
import {InteractionWorker} from '../../apps/worker/src/interactions.js';
import {ActionWorker} from '../../apps/worker/src/actions.js';
import {createApi} from '../../apps/api/src/server.js';
import {Queue,Worker} from 'bullmq';
let infra:Awaited<ReturnType<typeof infrastructure>>,db:Database,redis:Redis;
beforeAll(async()=>{infra=await infrastructure();db=connect(infra.databaseUrl);await migrate(db);redis=new Redis(infra.redisUrl);});
afterAll(async()=>{await redis?.quit();await db?.destroy();await infra?.stop();});
it('runs the entire signed-HTTP → BullMQ → outbox → Streams → overview → preferences slice',async()=>{
 const s=scopeForGuild('531111111111111111'),admin='531111111111111112',user='531111111111111113',channel='531111111111111114',role='531111111111111115';
 const vault=new IdentityVault('aa'.repeat(32),'bb'.repeat(32)),tokens=new Components('slice-component-key');
 const settings=new SettingsService(db),onboarding=new OnboardingService(db,settings,vault),discord=new FakeDiscord();
 const now=Date.now(),joined=new Date(now-8*86400000);
 discord.members.set(admin,{joinedAt:new Date(now-90*86400000).toISOString(),roles:[],permissions:'32',bot:false});
 discord.members.set(user,{joinedAt:joined.toISOString(),roles:[],permissions:'0',bot:false});
 const analytics=new AnalyticsService(db,settings),lifecycle=new LifecycleService(db,vault,settings,discord);
 const interactions=new InteractionWorker(db,vault,tokens,discord,settings,onboarding,async()=>{});
 const actions=new ActionWorker(db,vault,discord,onboarding);
 const keys=generateKeyPairSync('ed25519'),publicKey=keys.publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('hex');
 const http=createInteractionServer({db,vault,components:tokens,publicKey,applicationId:'531111111111111119'});
 const api=createApi(analytics,'slice-api-key');
 const redisUrl=new URL(infra.redisUrl),connection={host:redisUrl.hostname,port:Number(redisUrl.port)};
 const queueName=`slice-${randomUUID()}`,queue=new Queue(queueName,{connection});
 const worker=new Worker(queueName,async()=>{while(await interactions.tick(s)){/* drain durable jobs */}while(await actions.tick(s)){/* drain outbox */}},{connection});
 let sequence=0;
 const controls=(node:unknown):Record<string,unknown>[]=>{
  if(Array.isArray(node))return node.flatMap(controls);
  if(typeof node!=='object'||node===null)return [];
  const value=node as Record<string,unknown>;
  return [...(typeof value.custom_id==='string'?[value]:[]),...Object.values(value).flatMap(controls)];
 };
 const control=(label:string)=>{
  const found=controls(discord.panels.get('reply')).find(c=>c.label===label||c.placeholder===label);
  expect(found,`Missing control: ${label}`).toBeDefined();return String(found!.custom_id);
 };
 const deliver=async(userId:string,data:Record<string,unknown>,type=3)=>{
  const id=String(BigInt('631111111111111111')+BigInt(++sequence));
  const body=JSON.stringify({id,application_id:'531111111111111119',type,token:`token-${id}`,guild_id:s.guildId,channel_id:channel,
   member:{user:{id:userId},permissions:userId===admin?'32':'0',roles:[]},data});
  const ts=String(Math.floor(Date.now()/1000));const res=await http.inject({method:'POST',url:'/interactions',payload:body,headers:{'content-type':'application/json','x-signature-timestamp':ts,'x-signature-ed25519':sign(null,Buffer.from(ts+body),keys.privateKey).toString('hex')}});
  expect(res.statusCode).toBe(200);expect(res.json()).toEqual({type:5,data:{flags:64}});
  const job=await queue.add('interaction',{});
  await expect.poll(async()=> (await queue.getJob(job.id!))?.getState(),{timeout:10000}).toBe('completed');
 };
 try{
  await deliver(admin,{name:'nexus',options:[{name:'panel'}]},2);
  expect(JSON.stringify(discord.panels.get('reply'))).toContain('NEXUS panel is ready');
  await deliver(admin,{custom_id:control('Settings')});
  await deliver(admin,{custom_id:control('Advanced')});
  await deliver(admin,{custom_id:control('Choose community template'),values:['Gaming']});
  await deliver(admin,{custom_id:control('Choose a start channel'),values:[channel]});
  await deliver(admin,{custom_id:control('Enable onboarding')});
  await deliver(admin,{custom_id:control('Role mappings')});
  await deliver(admin,{custom_id:control('Choose an answer to map a role'),values:['purpose:community']});
  const roleSelect=controls(discord.panels.get('reply')).find(c=>c.type===6)!;
  await deliver(admin,{custom_id:roleSelect.custom_id,values:[role]});
  // This slice exercises the legacy start-channel success rule.
  const configured=await settings.get(s);await settings.update(s,{key:'admin',permissions:'32',roles:[],source:'DISCORD_PANEL',requestId:'legacy-slice'},configured.revision,{flags:{...configured.flags,activation_dsl_v2:false}});
  const publisher=new GatewayPublisher(redis),consumer=new StreamConsumer(redis,lifecycle,'slice-consumer',0);await consumer.init();
  const event=normalize({t:'GUILD_MEMBER_ADD',s:1,d:{guild_id:s.guildId,user:{id:user},joined_at:joined.toISOString()}},0,'slice-gateway',vault)!;
  await publisher.publish(event);await consumer.tick();
  await deliver(user,{name:'nexus',options:[{name:'personalize'}]},2);
  await deliver(user,{custom_id:controls(discord.panels.get('reply'))[0]!.custom_id,values:['community']});
  expect(discord.members.get(user)!.roles).toEqual([role]);
  const restart=control('Update Preferences / Restart Setup');
  await publisher.publish(normalize({t:'MESSAGE_CREATE',s:2,d:{guild_id:s.guildId,id:'531111111111111118',channel_id:channel,author:{id:user},type:0,timestamp:new Date(joined.getTime()+60000).toISOString()}},0,'slice-gateway',vault)!);await consumer.tick();
  await lifecycle.process({...s,shardId:0,gatewaySessionId:'slice-health',sequence:1,kind:'telemetry.connected',at:joined.toISOString(),context:'PRODUCTION'});
  await lifecycle.process({...s,shardId:0,gatewaySessionId:'slice-health',sequence:2,kind:'telemetry.heartbeat',at:new Date(joined.getTime()+30000).toISOString(),context:'PRODUCTION'});
  const url=`/v1/organizations/${s.organizationId}/guilds/${s.guildId}/overview`;
  const overview=await api.inject({url,headers:{authorization:`Bearer ${apiToken('slice-api-key',s)}`}});
  expect(overview.statusCode).toBe(200);expect(overview.json().metrics.activationRate.value).toBe(1);
  expect((await api.inject({url})).statusCode).toBe(403);
  expect((await api.inject({url,headers:{authorization:`Bearer ${apiToken('slice-api-key',scopeForGuild('531111111111111117'))}`}})).statusCode).toBe(403);
  await deliver(user,{custom_id:restart});
  await deliver(user,{custom_id:controls(discord.panels.get('reply'))[0]!.custom_id,values:['gaming']});
  await deliver(user,{custom_id:controls(discord.panels.get('reply'))[0]!.custom_id,values:['valorant']});
  expect(discord.members.get(user)!.roles).toEqual([]);
  expect((await sql`SELECT role_id FROM nexus_role_grants WHERE guild_id=${s.guildId} AND revoked_at IS NOT NULL`.execute(db)).rows).toHaveLength(1);
 }finally{await worker.close();await queue.close();await http.close();await api.close();}
});
it('uses real Streams, reclaims a crashed delivery and deduplicates lifecycle and activation',async()=>{
 const s=scopeForGuild('111111111111111113');await ensureGuild(db,s);
 const vault=new IdentityVault('aa'.repeat(32),'bb'.repeat(32));const settings=new SettingsService(db);const onboarding=new OnboardingService(db,settings,vault);const discord=new FakeDiscord();
 const user='111111111111111114',helper='111111111111111115',channel='111111111111111116';const now=Date.now();const join=new Date(now-8*86400000);
 discord.members.set(user,{joinedAt:join.toISOString(),roles:[],permissions:'0',bot:false});discord.members.set(helper,{joinedAt:new Date(now-30*86400000).toISOString(),roles:[],permissions:'0',bot:false});
 const actor={key:'admin',permissions:'32',roles:[],source:'DISCORD_PANEL' as const,requestId:randomUUID()};
 const cfg=await onboarding.chooseTemplate(s,actor,0,'Gaming');await settings.update(s,actor,cfg.revision,{enabled:true,onboardingEnabled:true,startChannelId:channel,flags:{...cfg.flags,activation_dsl_v2:false}});
 const lifecycle=new LifecycleService(db,vault,settings,discord);const publisher=new GatewayPublisher(redis);const worker=new StreamConsumer(redis,lifecycle,'worker-1',0);await worker.init();
 const joined=normalize({t:'GUILD_MEMBER_ADD',s:1,d:{guild_id:s.guildId,user:{id:user},joined_at:join.toISOString()}},0,'session',vault)!;
 const message=normalize({t:'MESSAGE_CREATE',s:2,d:{guild_id:s.guildId,id:'111111111111111117',channel_id:channel,author:{id:user},type:0,timestamp:new Date(join.getTime()+60000).toISOString(),content:'must never persist'}},0,'session',vault)!;
 // Deliberate order reversal; member lookup reconstructs the actual join timestamp.
 await publisher.publish(message);await publisher.publish(joined);await publisher.publish(message);
 await redis.xreadgroup('GROUP','lifecycle','dead-worker','COUNT',1,'STREAMS',STREAM,'>');
 for(let i=0;i<4;i++)await worker.tick();
 expect((await sql`SELECT id FROM lifecycle_events WHERE guild_id=${s.guildId} AND kind='message.sent'`.execute(db)).rows).toHaveLength(1);
 expect((await sql`SELECT id FROM lifecycle_events WHERE guild_id=${s.guildId} AND kind='activation.completed'`.execute(db)).rows).toHaveLength(1);
 const reply=normalize({t:'MESSAGE_CREATE',s:3,d:{guild_id:s.guildId,id:'111111111111111118',channel_id:channel,author:{id:helper},type:19,timestamp:new Date(join.getTime()+120000).toISOString(),message_reference:{message_id:message.messageId}}},0,'session',vault)!;
 await publisher.publish(reply);await worker.tick();
 const target=(await sql<{data:Record<string,unknown>}>`SELECT data FROM lifecycle_events WHERE guild_id=${s.guildId} AND kind='message.sent' AND data->>'messageId'=${message.messageId}`.execute(db)).rows[0]!;
 expect(target.data).toMatchObject({receivedExplicitReply:true,firstReplyLatencySeconds:60});expect(JSON.stringify(target)).not.toContain(helper);
 const health:Envelope={...s,shardId:0,gatewaySessionId:'health',sequence:1,kind:'telemetry.connected',at:join.toISOString(),context:'PRODUCTION'};
 await lifecycle.process(health);await lifecycle.process({...health,sequence:2,kind:'telemetry.heartbeat',at:new Date(join.getTime()+30000).toISOString()});
 await lifecycle.process({...health,sequence:3,kind:'telemetry.heartbeat',at:new Date(now).toISOString()});
 const metrics=await new AnalyticsService(db,settings).overview(s,join,new Date(now),new Date(now));
 expect(metrics.newMembers!.value).toBe(1);expect(metrics.activationRate!.value).toBe(1);expect(metrics.firstResponseRate!.value).toBe(1);expect(metrics.newMembers!.coverage).toBe('PARTIAL');
 expect((await redis.xpending(STREAM,'lifecycle'))[0]).toBe(0);
 const raw=JSON.stringify(await redis.xrange(STREAM,'-','+'));expect(raw).not.toContain('must never persist');expect(raw).not.toContain(user);
});
it('closes out-of-order leave/join episodes and creates a distinct rejoin',async()=>{
 const s=scopeForGuild('211111111111111113');await ensureGuild(db,s);
 const vault=new IdentityVault('aa'.repeat(32),'bb'.repeat(32));const settings=new SettingsService(db);const discord=new FakeDiscord();
 await settings.update(s,{key:'admin',permissions:'32',roles:[],source:'DISCORD_PANEL',requestId:'rejoin'},0,{enabled:true});
 const service=new LifecycleService(db,vault,settings,discord);const user='211111111111111114';
 const base={...s,shardId:0,gatewaySessionId:'rejoin',context:'PRODUCTION' as const,encryptedUserId:vault.seal(s,user)};
 await service.process({...base,sequence:1,kind:'member.left',at:'2026-09-10T00:00:00.000Z'});
 await service.process({...base,sequence:2,kind:'member.joined',at:'2026-09-01T00:00:00.000Z',joinedAt:'2026-09-01T00:00:00.000Z'});
 await service.process({...base,sequence:3,kind:'member.joined',at:'2026-09-12T00:00:00.000Z',joinedAt:'2026-09-12T00:00:00.000Z'});
 const episodes=(await sql<{left_at:Date|null}>`SELECT left_at FROM membership_episodes WHERE guild_id=${s.guildId} ORDER BY joined_at`.execute(db)).rows;
 expect(episodes).toHaveLength(2);expect(episodes[0]!.left_at?.toISOString()).toBe('2026-09-10T00:00:00.000Z');expect(episodes[1]!.left_at).toBeNull();
 await service.process({...base,gatewaySessionId:'new-gateway-session',sequence:1,kind:'member.joined',at:'2026-09-12T00:00:00.000Z',joinedAt:'2026-09-12T00:00:00.000Z'});
 expect((await sql`SELECT id FROM lifecycle_events WHERE guild_id=${s.guildId} AND kind='member.rejoined'`.execute(db)).rows).toHaveLength(1);
});
it('recovers a deleted consumer group and records stream loss as incomplete coverage',async()=>{
 const s=scopeForGuild('111111111111111113');const vault=new IdentityVault('aa'.repeat(32),'bb'.repeat(32));const service=new LifecycleService(db,vault,new SettingsService(db),new FakeDiscord());
 const consumer=new StreamConsumer(redis,service,'reset-consumer',0,()=>service.streamReset(s));
 await redis.del(STREAM);expect(await consumer.tick()).toBe(0);
 expect((await sql`SELECT id FROM telemetry_health WHERE guild_id=${s.guildId} AND reason='Redis stream reset'`.execute(db)).rows).toHaveLength(1);
 const event:Envelope={...s,shardId:0,gatewaySessionId:'post-reset',sequence:1,kind:'telemetry.heartbeat',at:new Date().toISOString(),context:'PRODUCTION'};
 await new GatewayPublisher(redis).publish(event);expect(await consumer.tick()).toBe(1);expect((await redis.xpending(STREAM,'lifecycle'))[0]).toBe(0);
});
it('does not starve fresh messages behind unresolved reply references',async()=>{
 const s=scopeForGuild('741111111111111111');await ensureGuild(db,s);const vault=new IdentityVault('aa'.repeat(32),'bb'.repeat(32));const settings=new SettingsService(db);const discord=new FakeDiscord();
 await settings.update(s,{key:'admin',permissions:'32',roles:[],source:'DISCORD_PANEL',requestId:'pending'},0,{enabled:true,flags:{...(await settings.get(s)).flags,activation_dsl_v2:false}});
 const now=Date.now(),user='741111111111111112',helper='741111111111111113',helper2='741111111111111117';
 discord.members.set(user,{joinedAt:new Date(now-60000).toISOString(),permissions:'0',roles:[],bot:false});discord.members.set(helper,{joinedAt:new Date(now-86400000).toISOString(),permissions:'0',roles:[],bot:false});discord.members.set(helper2,{...discord.members.get(helper)!});
 const service=new LifecycleService(db,vault,settings,discord),consumer=new StreamConsumer(redis,service,'reply-consumer',0),publisher=new GatewayPublisher(redis);await consumer.init();
 const target=normalize({t:'MESSAGE_CREATE',s:1,d:{guild_id:s.guildId,id:'741111111111111114',channel_id:'741111111111111115',author:{id:user},timestamp:new Date(now-20000).toISOString(),type:0}},0,'reply-order',vault)!;
 const reply=normalize({t:'MESSAGE_CREATE',s:2,d:{guild_id:s.guildId,id:'741111111111111116',channel_id:'741111111111111115',author:{id:helper},timestamp:new Date(now-10000).toISOString(),type:19,message_reference:{message_id:target.messageId}}},0,'reply-order',vault)!;
 await publisher.publish(reply);await consumer.tick();
 expect((await sql`SELECT id FROM telemetry_health WHERE guild_id=${s.guildId} AND reason LIKE 'pending:%'`.execute(db)).rows).toHaveLength(1);
 await publisher.publish(target);await consumer.tick();await consumer.tick();
 expect((await sql`SELECT id FROM telemetry_health WHERE guild_id=${s.guildId} AND reason LIKE 'pending:%'`.execute(db)).rows).toHaveLength(0);
 const earlierReply={...reply,sequence:3,messageId:'741111111111111118',encryptedUserId:vault.seal(s,helper2),at:new Date(now-15000).toISOString()};
 await Promise.all([service.process(earlierReply),service.process({...reply,sequence:4,messageId:'741111111111111119',at:new Date(now-5000).toISOString()})]);
 const message=(await sql<{data:{firstReplyLatencySeconds:number}}>`SELECT data FROM lifecycle_events WHERE guild_id=${s.guildId} AND data->>'messageId'=${target.messageId}`.execute(db)).rows[0]!;
 expect(message.data.firstReplyLatencySeconds).toBe(5);
});
it('records failed publication for its own guild when Redis becomes available again',async()=>{
 const client=new Redis(infra.redisUrl,{maxRetriesPerRequest:0,enableOfflineQueue:false,lazyConnect:true,retryStrategy:()=>null});client.on('error',()=>{});await client.connect();
 const publisher=new GatewayPublisher(client);await new Promise<void>(resolve=>{client.once('end',resolve);client.disconnect();});
 const event:Envelope={...scopeForGuild('851111111111111111'),shardId:0,gatewaySessionId:'redis-loss',sequence:1,kind:'telemetry.heartbeat',at:new Date().toISOString(),context:'PRODUCTION'};
 await expect(publisher.publish(event)).rejects.toThrow('Gateway stream unavailable');await client.connect();
 await publisher.publish({...event,...scopeForGuild('851111111111111112'),sequence:2});
 const entries=await client.xrange(STREAM,'-','+');const envelopes=entries.map(([,fields])=>JSON.parse(fields[1]!) as Envelope);
 expect(envelopes.some(e=>e.kind==='telemetry.gap'&&e.guildId===event.guildId)).toBe(true);await client.quit();
});
