import {sql,tenant,type Database} from '../../db/src/index.js';
import type {Scope} from '../../shared/src/index.js';
import {SettingsService} from '../../settings/src/index.js';

const DAY=86400000;
const ACTIVE=new Set(['message.sent','reaction.added','voice.started','voice.duration','scheduled_event.subscribed','fallback.answer','interaction.used','activation.completed']);
type Episode={id:string;identity_id:string;joined_at:Date;left_at:Date|null;roles:string[]|null};
type Fact={episode_id:string;kind:string;occurred_at:Date;data:Record<string,unknown>};
type Stage='new'|'starting'|'continuing'|'inactive'|'staff';
type Member={episode:Episode;stage:Stage;facts:Fact[];active:Fact[];days:Set<string>;channels:Set<string>;first:Fact|null;connected:Fact|null;repeated:boolean;retained:boolean;replyMinutes:number|null;voice:boolean;event:boolean;earlyChannels:Set<string>};
const channel=(fact:Fact)=>typeof fact.data.channelId==='string'?fact.data.channelId:null;
const percent=(part:number,total:number)=>total?Math.round(part/total*100):null;
export class CommunityService{
 constructor(private readonly db:Database,private readonly settings=new SettingsService(db)){}
 async overview(s:Scope,range:7|30|90=30,now=new Date(),autoStaffRoleIds:string[]=[]){
  const cfg=await this.settings.get(s),from=new Date(now.getTime()-Math.max(range,cfg.memberStages.recentDays,cfg.memberStages.retainedThroughDay+1)*DAY),cursor=(await sql<{first_seen:Date;last_seen:Date}>`SELECT first_seen,last_seen FROM telemetry_cursor WHERE ${tenant(s)}`.execute(this.db)).rows[0],gaps=(await sql<{started_at:Date;ended_at:Date|null}>`SELECT started_at,ended_at FROM telemetry_health WHERE ${tenant(s)} AND started_at<${now} AND (ended_at IS NULL OR ended_at>${from})`.execute(this.db)).rows;
  const episodes=(await sql<Episode>`SELECT e.id,e.identity_id,e.joined_at,e.left_at,st.roles FROM membership_episodes e LEFT JOIN member_observable_state st ON st.organization_id=e.organization_id AND st.guild_id=e.guild_id AND st.episode_id=e.id WHERE e.organization_id=${s.organizationId}::uuid AND e.guild_id=${s.guildId} AND e.context='PRODUCTION' AND (e.left_at IS NULL OR e.left_at>=${from})`.execute(this.db)).rows;
  const facts=(await sql<Fact>`SELECT f.episode_id,f.kind,f.occurred_at,f.data FROM lifecycle_events f WHERE ${tenant(s)} AND f.context='PRODUCTION' AND f.occurred_at>=${from} AND f.occurred_at<=${now} AND f.kind IN ('message.sent','reaction.added','voice.started','voice.duration','voice.connected','scheduled_event.subscribed','fallback.answer','interaction.used','role.added','reply.received','reply.established','activation.completed') ORDER BY f.occurred_at`.execute(this.db)).rows;
  const byEpisode=new Map<string,Fact[]>();for(const f of facts){const list=byEpisode.get(f.episode_id)??[];list.push(f);byEpisode.set(f.episode_id,list);}
  const allowed=(f:Fact)=>{const id=channel(f);return !id||cfg.analysisScope.mode==='all'||(cfg.analysisScope.mode==='include')===cfg.analysisScope.channelIds.includes(id);};
  const staffRoles=new Set([...cfg.staffRoleIds,...autoStaffRoleIds]);
  const members:Member[]=episodes.map(episode=>{const all=(byEpisode.get(episode.id)??[]).filter(allowed),active=all.filter(f=>ACTIVE.has(f.kind)),days=new Set(active.map(f=>f.occurred_at.toISOString().slice(0,10))),channels=new Set(active.map(channel).filter((id):id is string=>id!==null)),age=(now.getTime()-episode.joined_at.getTime())/DAY,staff=episode.roles?.some(role=>staffRoles.has(role))??false,stage:Stage=staff?'staff':age<=cfg.memberStages.newDays?'new':age<=cfg.memberStages.startingDays?'starting':new Set(active.filter(f=>f.occurred_at.getTime()>=now.getTime()-cfg.memberStages.recentDays*DAY).map(f=>f.occurred_at.toISOString().slice(0,10))).size>=cfg.memberStages.activeDays?'continuing':'inactive',first=active.find(f=>f.occurred_at.getTime()<=episode.joined_at.getTime()+cfg.activationWindowHours*3600000)??null,connected=all.find(f=>f.kind==='reply.received'||f.kind==='reply.established'||f.kind==='voice.connected')??null,earlyChannels=new Set(active.filter(f=>f.occurred_at.getTime()<episode.joined_at.getTime()+3*DAY).map(channel).filter((id):id is string=>id!==null)),reply=all.find(f=>f.kind==='reply.received'),earlyDays=new Set(active.filter(f=>f.occurred_at.getTime()<episode.joined_at.getTime()+cfg.memberStages.retainedFromDay*DAY).map(f=>f.occurred_at.toISOString().slice(0,10)));return {episode,stage,facts:all,active,days,channels,first,connected,repeated:earlyDays.size>=cfg.memberStages.repeatDays,retained:active.some(f=>{const elapsed=(f.occurred_at.getTime()-episode.joined_at.getTime())/DAY;return elapsed>=cfg.memberStages.retainedFromDay&&elapsed<cfg.memberStages.retainedThroughDay;}),replyMinutes:typeof reply?.data.latencySeconds==='number'?reply.data.latencySeconds/60:null,voice:active.some(f=>f.kind==='voice.started'||f.kind==='voice.duration'),event:active.some(f=>f.kind==='scheduled_event.subscribed'),earlyChannels};});
  const observed=(a:Date,b:Date)=>Boolean(cursor&&cursor.first_seen<=a&&cursor.last_seen>=b&&!gaps.some(g=>g.started_at<b&&(g.ended_at===null||g.ended_at>a)));
  const entered=members.filter(m=>m.stage!=='staff'&&m.episode.joined_at>=new Date(now.getTime()-range*DAY)&&m.episode.joined_at<=now&&Boolean(cursor&&m.episode.joined_at>=cursor.first_seen));
  const eligible=entered.filter(m=>m.episode.joined_at.getTime()>=now.getTime()-cfg.detailedRetentionDays*DAY&&observed(m.episode.joined_at,new Date(m.episode.joined_at.getTime()+cfg.memberStages.retainedThroughDay*DAY)));
  const steps=[{key:'joined',label:'参加した',count:eligible.length},{key:'activated',label:'最初の活動をした',count:eligible.filter(m=>m.first).length},{key:'connected',label:'誰かと交流できた',count:eligible.filter(m=>m.first&&m.connected&&m.connected.occurred_at>=m.first.occurred_at).length},{key:'repeated',label:'別の日にも参加した',count:eligible.filter(m=>m.first&&m.connected&&m.repeated).length},{key:'retained',label:'1週間後も活動が確認できた',count:eligible.filter(m=>m.first&&m.connected&&m.repeated&&m.retained).length}];
  const drops=steps.slice(1).map((step,i)=>({fromKey:steps[i]!.key,toKey:step.key,from:steps[i]!.label,to:step.label,count:steps[i]!.count-step.count}));const largest=drops.sort((a,b)=>b.count-a.count)[0]??null;
  const summarize=(group:Member[],window:'early'|'recent')=>{const subset=(m:Member)=>m.facts.filter(f=>window==='early'?f.occurred_at>=m.episode.joined_at&&f.occurred_at<new Date(m.episode.joined_at.getTime()+3*DAY):f.occurred_at>=new Date(now.getTime()-3*DAY)),replies=group.map(m=>subset(m).find(f=>f.kind==='reply.received')).map(f=>f?.data.latencySeconds).filter((n):n is number=>typeof n==='number');return {members:group.length,receivedReplyPercent:percent(replies.length,group.length),replyMinutes:replies.length?Math.round(replies.reduce((a,b)=>a+b,0)/replies.length/60):null,activeDays:group.length?Math.round(group.reduce((n,m)=>n+new Set(subset(m).filter(f=>ACTIVE.has(f.kind)).map(f=>f.occurred_at.toISOString().slice(0,10))).size,0)/group.length*10)/10:null,channelCount:group.length?Math.round(group.reduce((n,m)=>n+new Set(subset(m).filter(f=>ACTIVE.has(f.kind)).map(channel).filter(Boolean)).size,0)/group.length*10)/10:null,voicePercent:percent(group.filter(m=>subset(m).some(f=>f.kind==='voice.started'||f.kind==='voice.duration')).length,group.length),eventPercent:percent(group.filter(m=>subset(m).some(f=>f.kind==='scheduled_event.subscribed')).length,group.length)};};
  const newcomers=entered.filter(m=>m.episode.joined_at<=new Date(now.getTime()-3*DAY)&&observed(m.episode.joined_at,new Date(m.episode.joined_at.getTime()+3*DAY))),continuing=members.filter(m=>m.stage==='continuing'),recentObserved=Boolean(cursor&&cursor.last_seen.getTime()>=now.getTime()-10*60*1000&&observed(new Date(now.getTime()-3*DAY),cursor.last_seen)),comparisonContinuing=recentObserved?continuing:[];
  const compare={newcomers:newcomers.length>=5?summarize(newcomers,'early'):null,continuing:comparisonContinuing.length>=5?summarize(comparisonContinuing,'recent'):null,available:newcomers.length>=5&&comparisonContinuing.length>=5};
  const settled=eligible.filter(m=>m.episode.joined_at>=new Date(now.getTime()-range*DAY));const retained=settled.filter(m=>m.retained),notRetained=settled.filter(m=>!m.retained),pending=entered.filter(m=>m.episode.joined_at.getTime()+cfg.memberStages.retainedThroughDay*DAY>now.getTime()).length,insufficient=entered.length-settled.length-pending;const outcomes={retained:retained.length,notRetained:notRetained.length,pending,insufficient,patterns:retained.length>=5&&notRetained.length>=5?{retained:summarize(retained,'early'),notRetained:summarize(notRetained,'early')}:null};
  const channels=new Map<string,Member[]>(),channelPeople=new Map<string,Set<string>>();for(const member of entered){for(const id of member.earlyChannels){const people=channelPeople.get(id)??new Set<string>();if(!people.has(member.episode.identity_id)){const group=channels.get(id)??[];group.push(member);channels.set(id,group);people.add(member.episode.identity_id);channelPeople.set(id,people);}}}
  const channelSummary=[...channels].filter(([,group])=>group.length>=3).map(([id,group])=>{const replyGroup=group.filter(m=>observed(m.episode.joined_at,new Date(m.episode.joined_at.getTime()+DAY))),laterGroup=group.filter(m=>observed(m.episode.joined_at,new Date(m.episode.joined_at.getTime()+3*DAY))),weekGroup=group.filter(m=>eligible.includes(m));return {channelId:id,newcomers:group.length,receivedReplyPercent:replyGroup.length>=3?percent(replyGroup.filter(m=>m.facts.some(f=>f.kind==='reply.received'&&f.occurred_at.getTime()<m.episode.joined_at.getTime()+DAY)).length,replyGroup.length):null,laterElsewherePercent:laterGroup.length>=3?percent(laterGroup.filter(m=>m.active.some(f=>channel(f)!==null&&channel(f)!==id&&f.occurred_at.getTime()<m.episode.joined_at.getTime()+3*DAY)).length,laterGroup.length):null,weekLaterPercent:weekGroup.length>=3?percent(weekGroup.filter(m=>m.retained).length,weekGroup.length):null};}).sort((a,b)=>b.newcomers-a.newcomers);
  const transitionPeople=new Map<string,Set<string>>();for(const m of entered){const path:string[]=[];for(const fact of m.active){const id=channel(fact)??(fact.kind.startsWith('voice.')?'voice':null);if(id&&path.at(-1)!==id)path.push(id);}for(let i=1;i<path.length;i++){const key=`${path[i-1]}:${path[i]}`,people=transitionPeople.get(key)??new Set<string>();people.add(m.episode.identity_id);transitionPeople.set(key,people);}}
  const transitions=[...transitionPeople].filter(([,people])=>people.size>=3).map(([path,people])=>({from:path.split(':')[0]!,to:path.split(':')[1]!,count:people.size})).sort((a,b)=>b.count-a.count).slice(0,20);
  const suggestion=compare.available&&compare.newcomers!.replyMinutes!==null&&compare.continuing!.replyMinutes!==null&&compare.newcomers!.replyMinutes>compare.continuing!.replyMinutes*1.5&&compare.newcomers!.replyMinutes-compare.continuing!.replyMinutes>=10?{key:'reply_rescue',text:'新しいメンバーへの返信が普段参加している人より遅い傾向があります。返信待ちの投稿をスタッフに知らせる改善テストを検討できます。',basis:{newcomerMinutes:compare.newcomers!.replyMinutes,continuingMinutes:compare.continuing!.replyMinutes}}:null;
  return {generatedAt:now.toISOString(),range,scope:cfg.analysisScope,arrivalCount:entered.length,stages:steps,eligibleMembers:eligible.length,largestDrop:eligible.length>=5?largest:null,classification:{new:members.filter(m=>m.stage==='new').length,starting:members.filter(m=>m.stage==='starting').length,continuing:continuing.length,inactive:members.filter(m=>m.stage==='inactive').length,staffExcluded:members.filter(m=>m.stage==='staff').length},compare,outcomes,channels:channelSummary,hiddenChannelCount:channels.size-channelSummary.length,transitions,suggestion,dataReady:eligible.length>=5,observation:'Discordで確認できた活動のみを集計しています。閲覧だけの参加は観測できません。'};
 }
}
