import {connectionStateLabel} from '../../../../packages/discord-panels/src/i18n/terminology';
import type {AuthorizedGuild} from '../auth/session';
import type {SiteLocale} from '../public-ui';

export function ServerCards({locale,guilds}:{locale:SiteLocale;guilds:AuthorizedGuild[]}){
 const copy=(ja:string,en:string)=>locale==='ja'?ja:en;
 const icons={VERIFIED:"●",INSTALLED_NOT_VERIFIED:"◐",VERIFICATION_PENDING:"◷",NOT_INSTALLED:"○"};
 return <div className="server-list">{guilds.map(g=><article className="server-card" key={g.id} data-state={g.availability??g.state}><div className="server-icon" aria-hidden="true">{g.name.trim().slice(0,1).toUpperCase()}</div><div><h2>{g.name}</h2><p>{g.availability==='UNAVAILABLE'?copy('接続状態を取得できませんでした','Connection status unavailable'):`${icons[g.state]} ${connectionStateLabel(locale,g.state)}`}</p>{g.failure?.reference&&<small>{copy('参照ID','Reference ID')}: {g.failure.reference}</small>}{g.availability!=='UNAVAILABLE'&&g.installed&&g.state!=='VERIFIED'&&<p>{copy('Discordで /nexus link を実行してください。','Run /nexus link in Discord.')}</p>}</div>{g.availability==='UNAVAILABLE'?<a className="button button-secondary" href="/servers">{copy('再試行','Retry')}</a>:g.state==='VERIFIED'?<a className="button button-primary" href={`/auth/select?guild=${encodeURIComponent(g.id)}`}>{copy('Dashboardを開く','Open Dashboard')}</a>:g.installed?<a className="button button-primary" href="/link">{copy('Web Dashboardを接続','Connect Web Dashboard')}</a>:g.installUrl&&<a className="button button-discord" href={g.installUrl}>{copy('NEXUSを追加','Add NEXUS')}</a>}</article>)}{!guilds.length&&<div className="server-empty"><h2>{copy('管理できるサーバーがありません','No manageable servers found')}</h2><p>{copy('サーバー管理権限または設定済みNEXUS管理ロールが必要です。','You need server management permission or a configured NEXUS manager role.')}</p></div>}</div>;
}
