export type ErrorCategory='BETA_ACCESS'|'BETA_USAGE'|'ANALYSIS_USAGE'|'ANALYSIS_RESULT'|'PERMISSION'|'CHANNEL_PERMISSION'|'REVISION_CONFLICT'|'COMPONENT_EXPIRED'|'DISCORD_TIMEOUT'|'DISCORD_RATE_LIMIT'|'DISCORD_UNAVAILABLE'|'DATABASE_FAILURE'|'VALIDATION'|'ENTITLEMENT'|'WEB_CONNECTION'|'AUTH_SESSION'|'VERIFICATION'|'INTERNAL';
export type FailureEffect='NOT_STARTED'|'UNKNOWN';
export type UserFailure={category:ErrorCategory;reference?:string;effect:FailureEffect};
