import {ButtonStyle,ComponentType,type APIButtonComponent,type APIStringSelectComponent,type APIChannelSelectComponent,type APIRoleSelectComponent} from 'discord-api-types/v10';
import type {CommunityService} from '../../../presentation/src/community.js';
import {t,type UiLocale} from '../i18n/index.js';
import {actionRow,callout,divider,footer,metricGrid,nexusPanel,type ActionRow,type ButtonSpec,type Panel} from '../primitives.js';
import {homeContent,measurementLabel} from './home.js';
import {activityWindow} from '../i18n/terminology.js';
import type {Issue} from '../types.js';
import type {CommunityModel,CapabilitySnapshot} from '../../../shared/src/community-model.js';
import {modeNames,statusNames,featureNames,metricCopy} from '../../../shared/src/community-copy.js';

export const controlPages=['overview','newMembers','attention','analysis','results','settings'] as const;
export type ControlPage=typeof controlPages[number]|'channels'|'community'|'improve'|'diagnostics';
export const settingsSections=['main','model','scope','team','notifications','goals','summary','privacy','panel','diagnostics','advanced'] as const;
export type SettingsSection=typeof settingsSections[number];
export const analysisViews=['overall','channels','behavior'] as const;
export type AnalysisView=typeof analysisViews[number];
type Community=Awaited<ReturnType<CommunityService['overview']>>;
export type ControlData={
 model?:{profile:CommunityModel;capabilities:CapabilitySnapshot|null;revision:number};
 community?:Community|null;
 settings?:{analysisScope:{mode:string;channelIds:string[]};managerRoleIds:string[];helperRoleIds:string[];weeklySummaryEnabled:boolean;weeklySummaryChannelId:string|null;weeklySummaryDay:number;weeklySummaryHour:number;timezone:string;helperEnabled:boolean;helperChannelId:string|null;firstResponseMinutes:number;goalPreset:'multiplayer'|'early_access'|'live_service'|null;newMemberGoals:string[];importantChannels:{channelId:string;purpose:string}[];uiLanguage:string;detailedRetentionDays:number;revision:number;setupVersion?:number;panelChannelId?:string|null;setupSteps?:{scope:boolean;team:boolean;notifications:boolean;goals:boolean}};
 results?:{controlRate:number|null;treatmentRate:number|null;controlN:number;treatmentN:number;state:string}|null;
 diagnostics?:{version?:string;buildSha?:string;releaseChannel?:string;gatewayConnected:boolean;transport:'gateway'|'webhook';commandsRegistered:boolean;lastReceivedAt:string|null;lastAcknowledgedAt:string|null;lastCompletedAt:string|null;lastResult:string|null;lastActivityAt:string|null;databaseConnected:boolean;redisConnected:boolean};
 dashboardUrl?:string;
 webVerified?:boolean;
 updatedAt?:Date;
};
const percent=(value:number|null|undefined)=>value===null||value===undefined?'—':`${value}%`;
const rate=(value:number|null|undefined)=>value===null||value===undefined?'—':`${Math.round(value*100)}%`;
const date=(value:string,locale:UiLocale)=>new Intl.DateTimeFormat(locale==='en'?'en-US':'ja-JP',{timeZone:'UTC',year:'numeric',month:'short',day:'numeric'}).format(new Date(value));
const relative=(value:string)=>`<t:${Math.floor(new Date(value).getTime()/1000)}:R>`;

export async function panelPlacementWarning(issue:Issue,channelId:string,locale:UiLocale='en'){
 return nexusPanel({title:t(locale,'control.publicWarningTitle'),children:[divider(),callout(t(locale,'control.publicWarningTitle'),t(locale,'control.publicWarningDetail'))],rows:[await actionRow(issue,[{label:t(locale,'control.installHere'),action:'panelConfirm',data:{channelId},style:ButtonStyle.Danger},{label:t(locale,'control.chooseAnother'),action:'panelChoose'}])]});
}

export async function controlPanel(issue:Issue,page:ControlPage,data:ControlData,locale:UiLocale='en',section:SettingsSection='main',channelPage=0,summaryField:'none'|'channel'|'day'|'hour'|'timezone'='none',goalPurpose:'none'|'lfg'|'feedback'|'bug'|'playtest'='none',analysisView:AnalysisView='overall',attentionIndex=0):Promise<Panel>{
 const children=[divider()],community=data.community;
 if(community?.adaptive&&['overview','newMembers','analysis','community'].includes(page)){const model=community.adaptive,ja=locale==='ja';children.splice(1);children.push(callout(ja?'運営目的':'Community purposes',model.profile.modes.map(m=>modeNames[m][ja?0:1]).join(' · ')||(ja?'設定から運営目的を選んでください。':'Choose community purposes in Settings.')));children.push(metricGrid([{label:ja?'観測対象':'Eligible members',value:String(model.eligible)},{label:ja?'ルール確認待ち':'Screening pending',value:String(model.pending)},{label:'Guest',value:String(model.guests)}]));if(model.progress&&page==='newMembers'){const p=model.progress;children.push(callout(ja?'新規メンバーの参加状況':'New member participation',`${ja?'観測対象':'Observed sample'} ${p.eligible} · ${p.observationDays} ${ja?'日':'days'}\n${ja?'最初の活動':'First activity'} ${p.first} / ${p.eligible} · ${ja?'応答・一定時間の同席':'Response/co-presence'} ${p.connected} / ${p.eligible}\n${ja?'複数日の参加':'Multiple days'} ${p.repeated} / ${p.eligible} · ${ja?'後日の参加':'Later participation'} ${p.retained} / ${p.eligible}\n${ja?'観測途中':'Still observing'} ${p.pending} · ${ja?'観測不足':'Insufficient coverage'} ${p.insufficient}`));}for(const metric of model.metrics.slice(0,6)){const copy=metricCopy(metric,ja?'ja':'en');children.push(callout(copy.label,`${metric.count??'—'}${metric.medianMinutes!=null?` · ${ja?'中央値':'median'} ${Math.round(metric.medianMinutes)} min`:''}\n${copy.definition}\n${ja?'観測人数・件数':'Sample'} ${metric.sample}${metric.denominator===null?'':` / ${metric.denominator}`}`));}children.push(footer(`${model.window.from.slice(0,10)} — ${model.window.through.slice(0,10)} · ${model.coverage.observableChannels} / ${model.coverage.totalRelevantChannels} · ${ja?'一部のみ観測。サーバー全体とは限りません。':'Partial coverage; not necessarily the entire server.'}`));const navigation:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlNavigate'},true),placeholder:t(locale,'control.choosePage'),options:controlPages.map(value=>({label:t(locale,`control.${value}`),value,default:page===value}))} satisfies APIStringSelectComponent]};const links=await actionRow(issue,[{label:t(locale,'control.model'),action:'controlSettings',data:{section:'model',privateSettings:true},publicEntry:true},{label:t(locale,'control.refresh'),action:'controlRefresh',data:{page},publicEntry:true}]);if(data.dashboardUrl)links.components.push({type:ComponentType.Button,style:ButtonStyle.Link,label:t(locale,'control.openWeb'),url:data.dashboardUrl});return nexusPanel({title:t(locale,'control.title'),children,rows:[navigation,links]});}
 const retentionTitle=activityWindow(locale==='en'?'en':'ja',community?.analysis?.rules.retainedFromDay,community?.analysis?.rules.retainedThroughDay);
 if(page==='overview'||page==='newMembers'){
  if(page==='overview'&&data.settings?.setupVersion===1)children.push(callout(t(locale,'control.setupUpgrade'),t(locale,'control.setupGuide')));
  if(page==='overview'){
   children.push(...homeContent(data,locale));
   if(community?.daily.attentionCount)children.splice(2,0,await actionRow(issue,[{label:t(locale,'control.attention'),action:'controlNavigate',data:{page:'attention'},publicEntry:true,emoji:'📥',style:ButtonStyle.Primary}]));
  }
  if(page==='overview'&&data.settings?.setupSteps){const done=Object.values(data.settings.setupSteps).filter(Boolean).length;if(done<4)children.push(callout(t(locale,'control.setupProgress',{done}),t(locale,'control.setupGuide')));}
  if(community){
   if(page==='newMembers'){
    const settled=community.outcomes.retained+community.outcomes.notRetained;
    children.push(metricGrid([{label:t(locale,'control.joined'),value:community.daily.ready?String(community.arrivalCount):t(locale,'polish.unavailable'),note:t(locale,'control.days',{count:community.range})},{label:t(locale,'control.connected'),value:!community.daily.ready?t(locale,'polish.unavailable'):community.eligibleMembers===0?t(locale,community.arrivalCount?'experience.pending':'polish.noMembers'):community.dataReady?`${community.stages[2]?.count??0} / ${community.eligibleMembers}`:t(locale,'control.noComparison'),note:t(locale,'experience.observed',{count:community.eligibleMembers})},{label:retentionTitle,value:measurementLabel(community.analysis?.retention,locale),note:settled?t(locale,'experience.observed',{count:settled}):t(locale,'experience.noMature')} ]));
    if(community.channels.length)children.push(callout(t(locale,'control.channels'),community.channels.slice(0,3).map(row=>`<#${row.channelId}> · ${row.newcomers}`).join('\n')));
    children.push(callout(t(locale,'experience.rules'),t(locale,'experience.connectionRule')));
    children.push(callout(t(locale,'polish.receivedTotal'),`${community.reactionsReceived??0} · ${t(locale,'control.days',{count:community.range})}\n${t(locale,'polish.receivedRule')}`));
    const window=community.cohortWindow;
    children.push(footer(`${t(locale,'control.joinedPeriod',{from:date(window.joinedFrom,locale),through:date(new Date(new Date(window.joinedThrough).getTime()-1).toISOString(),locale),days:window.observedThroughDays})} ${t(locale,'control.sample',{count:community.eligibleMembers})}`));
   }
  }else children.push(callout(t(locale,'control.newMembers'),t(locale,'control.moreData')));
 }else if(page==='attention'){
  if(!community?.daily.ready)children.push(callout(t(locale,'control.attention'),t(locale,'control.queueUnavailable')));
  else if(community.attention.length){const index=Math.min(attentionIndex,community.attention.length-1),item=community.attention[index]!,status={OPEN:locale==='ja'?'返信待ち':'Waiting for reply',ACKNOWLEDGED:t(locale,'experience.staffAcknowledged'),SNOOZED:locale==='ja'?'再確認待ち':'Snoozed',RESOLVED:t(locale,'control.resolve')}[item.status]??item.status;children.push(callout(`⏳ ${t(locale,'control.attention')} · ${attentionIndex+1} / ${community.daily.attentionCount??community.attention.length}`,`<#${item.channelId}> · ${t(locale,'control.minutes',{count:item.waitingMinutes})}\n${status}`));children.push(callout(t(locale,'experience.rules'),`${t(locale,'experience.waitReason')}\n${t(locale,'experience.queueRule',{count:data.settings?.firstResponseMinutes??20})}`));children.push(callout(t(locale,'control.openPost'),item.url));}
  else children.push(callout(`✅ ${t(locale,'experience.allClear')}`,t(locale,'experience.queueRule',{count:data.settings?.firstResponseMinutes??20})));
 }else if(page==='community'||page==='analysis'&&analysisView==='overall'){
  const analysis=community?.analysis,metric=analysis?.retention;
  children.push(callout(t(locale,'control.newMembers'),metric?.value!==null&&metric?.value!==undefined?t(locale,'control.days',{count:community!.range}):measurementLabel(metric,locale)));
  if(analysis){children.push(metricGrid([{label:t(locale,'control.joined'),value:analysis.joined===null?t(locale,'polish.unavailable'):t(locale,'polish.people',{count:analysis.joined}),note:t(locale,'control.days',{count:community!.range})},{label:retentionTitle,value:measurementLabel(metric,locale),note:metric?`${metric.numerator} / ${metric.sample} ${locale==='en'?'members':'人'} · ${date(metric.from,locale)}〜${date(new Date(new Date(metric.through).getTime()-1).toISOString(),locale)}`:undefined},{label:t(locale,'control.exited'),value:analysis.exited===null?t(locale,'polish.unavailable'):t(locale,'polish.people',{count:analysis.exited}),note:t(locale,'control.days',{count:community!.range})}]));
   if(metric?.previous!==null&&metric?.value!==null)children.push(callout(t(locale,'polish.week'),`${locale==='en'?'Previous comparison period':'前の比較期間'}: ${metric?.previous}% → ${metric?.value}%`));
   children.push(callout(t(locale,'experience.rules'),`${t(locale,'control.staffExcluded')}: ${community!.classification.staffExcluded}\n${locale==='en'?'Recent activity rule':'最近の活動の基準'}: ${analysis.rules.recentDays}${locale==='en'?' days; at least ':'日間に'}${analysis.rules.activeDays}${locale==='en'?' active days':'日以上の活動'}\n${t(locale,'control.observation')}`));
  }
  if(community?.compare.available)children.push(callout(t(locale,'control.replyComparison',{new:community.compare.newcomers?.replyMinutes??'—',regular:community.compare.continuing?.replyMinutes??'—'}),t(locale,'experience.sampleNotice')));
 }else if(page==='channels'||page==='analysis'&&analysisView==='channels'){
  if(community?.channels.length){const start=Math.min(channelPage*5,Math.max(0,Math.ceil(community.channels.length/5)-1)*5);children.push(callout(retentionTitle,t(locale,'experience.retentionRule')),callout(t(locale,'control.channels'),t(locale,'control.channelRange',{from:start+1,to:Math.min(start+5,community.channels.length),total:community.channels.length})));for(const channel of community.channels.slice(start,start+5)){const purpose=community.importantPlaces.find(item=>item.channelId===channel.channelId)?.purpose;children.push(callout(`<#${channel.channelId}>${purpose?` · ${t(locale,`goal.${purpose}`)}`:''}`,t(locale,'control.channelLine',{count:channel.newcomers,reply:percent(channel.receivedReplyPercent),elsewhere:percent(channel.laterElsewherePercent),later:percent(channel.weekLaterPercent)})));}
   if(community.transitions.length)children.push(callout(t(locale,'control.moves'),community.transitions.slice(0,3).map(move=>`${move.from==='voice'?t(locale,'control.voice'):`<#${move.from}>`} → ${move.to==='voice'?t(locale,'control.voice'):`<#${move.to}>`}`).join('\n')));
   if(community.hiddenChannelCount)children.push(footer(t(locale,'control.hiddenChannels',{count:community.hiddenChannelCount})));
  }else children.push(callout(t(locale,'control.channels'),t(locale,'control.noChannels')));
 }else if(page==='analysis'&&analysisView==='behavior'){
  if(community?.compare.available)children.push(metricGrid([{label:t(locale,'control.replyAlert'),value:percent(community.compare.newcomers?.receivedReplyPercent)},{label:t(locale,'control.voice'),value:percent(community.compare.newcomers?.voicePercent)},{label:t(locale,'control.goalEvent'),value:percent(community.compare.newcomers?.eventPercent)}]));
  else children.push(callout(t(locale,'control.analysis'),t(locale,'control.noComparison')));
  if(community?.transitions.length)children.push(callout(t(locale,'control.moves'),community.transitions.slice(0,3).map(move=>`${move.from==='voice'?t(locale,'control.voice'):`<#${move.from}>`} → ${move.to==='voice'?t(locale,'control.voice'):`<#${move.to}>`}`).join('\n')));
 }else if(page==='improve'){
  children.push(callout(t(locale,'control.improve'),community?.suggestion?.key==='reply_rescue'?t(locale,'control.replySuggestion'):t(locale,'control.noSuggestion')));
  if(community?.suggestion?.key==='reply_rescue')children.push(metricGrid([{label:t(locale,'control.newMembers'),value:t(locale,'control.minutes',{count:community.suggestion.basis.newcomerMinutes})},{label:t(locale,'control.regularMembers'),value:t(locale,'control.minutes',{count:community.suggestion.basis.continuingMinutes})}]));
 }
 else if(page==='results')children.push(data.results?metricGrid([{label:t(locale,'control.usual'),value:rate(data.results.controlRate),note:t(locale,'control.members',{count:data.results.controlN})},{label:t(locale,'control.withImprovement'),value:rate(data.results.treatmentRate),note:t(locale,'control.members',{count:data.results.treatmentN})}]):callout(t(locale,'control.results'),t(locale,'control.noResults')));
 else if(page==='settings'){
  const s=data.settings;if(!s)children.push(callout(t(locale,'control.settings'),t(locale,'control.moreData')));
  else if(section==='main')children.push(metricGrid([{label:t(locale,'polish.measurementScope'),value:t(locale,`control.scope${s.analysisScope.mode==='all'?'All':s.analysisScope.mode==='include'?'Include':'Exclude'}`)},{label:t(locale,'polish.waiting'),value:t(locale,'control.minutes',{count:s.firstResponseMinutes})},{label:t(locale,'control.notifications'),value:`${t(locale,s.helperEnabled?'control.on':'control.off')} · ${s.helperChannelId?`<#${s.helperChannelId}>`:t(locale,'common.notConfigured')}`},{label:t(locale,'polish.goals'),value:String(s.newMemberGoals.length)},{label:t(locale,'control.weekly'),value:t(locale,s.weeklySummaryEnabled?'control.on':'control.off')}]));
  else if(section==='scope')children.push(callout(t(locale,'control.scope'),`${t(locale,`control.scope${s.analysisScope.mode==='all'?'All':s.analysisScope.mode==='include'?'Include':'Exclude'}`)}\n${t(locale,'control.selectedChannels',{count:s.analysisScope.channelIds.length})}`));
  else if(section==='team')children.push(metricGrid([{label:t(locale,'control.managers'),value:s.managerRoleIds.length?s.managerRoleIds.map(id=>`<@&${id}>`).join(' '):t(locale,'control.ownerAdmins')},{label:t(locale,'control.helpers'),value:s.helperRoleIds.length?s.helperRoleIds.map(id=>`<@&${id}>`).join(' '):t(locale,'common.notConfigured')}]));
  else if(section==='notifications')children.push(metricGrid([{label:t(locale,'control.replyAlert'),value:t(locale,s.helperEnabled?'control.on':'control.off')},{label:t(locale,'control.destination'),value:s.helperChannelId?`<#${s.helperChannelId}>`:t(locale,'common.notConfigured')},{label:t(locale,'control.afterMinutes'),value:t(locale,'control.minutes',{count:s.firstResponseMinutes})},{label:t(locale,'control.helpers'),value:s.helperRoleIds.length?s.helperRoleIds.slice(0,3).map(id=>`<@&${id}>`).join(' '):t(locale,'common.notConfigured')},{label:t(locale,'control.dailyLimit'),value:t(locale,'control.alertLimit')}]));
  else if(section==='goals'){
   children.push(callout(t(locale,'control.goals'),(['reply','lfg','voice','event','feedback','bug','playtest'] as const).map(goal=>`${s.newMemberGoals.includes(goal)?'☑':'☐'} ${t(locale,`control.goal${goal[0]!.toUpperCase()+goal.slice(1)}` as 'control.goalReply')}`).join('\n')));
   children.push(callout(t(locale,'experience.rules'),`${t(locale,'experience.replyRule')}\n${t(locale,'experience.voiceRule')}\n${t(locale,'experience.eventRule')}\n${t(locale,'experience.channelRule')}`));
   if(s.goalPreset)children.push(callout(t(locale,'control.gameType'),`${t(locale,`goal.${s.goalPreset}`)} · ${t(locale,`control.recommend${s.goalPreset==='multiplayer'?'Multiplayer':s.goalPreset==='early_access'?'EarlyAccess':'LiveService'}`)}`));
   if(s.importantChannels.length)children.push(callout(t(locale,'control.goalChannels'),s.importantChannels.map(item=>`${t(locale,`goal.${item.purpose as 'lfg'}`)}: <#${item.channelId}>`).join('\n')));
  }
  else if(section==='summary')children.push(metricGrid([{label:t(locale,'control.weekly'),value:t(locale,s.weeklySummaryEnabled?'control.on':'control.off')},{label:t(locale,'control.destination'),value:s.weeklySummaryChannelId?`<#${s.weeklySummaryChannelId}>`:t(locale,'common.notConfigured')},{label:t(locale,'control.day'),value:t(locale,`control.day${s.weeklySummaryDay}` as 'control.day0')},{label:t(locale,'control.time'),value:`${String(s.weeklySummaryHour).padStart(2,'0')}:00 · ${s.timezone}`}]));
  else if(section==='privacy')children.push(metricGrid([{label:t(locale,'control.messageText'),value:t(locale,'control.notStored')},{label:t(locale,'control.detailRetention'),value:t(locale,'control.days',{count:s.detailedRetentionDays})}]));
  else if(section==='panel')children.push(callout(t(locale,'control.panel'),s.panelChannelId?`<#${s.panelChannelId}>`:t(locale,'common.notConfigured')));
  else if(section==='diagnostics')children.push(callout(t(locale,'control.diagnostics'),t(locale,'control.diagnosticsHint')));
  else children.push(callout(t(locale,'control.advanced'),t(locale,'control.advancedDetail')));
 }
 else if(page==='diagnostics')children.push(data.diagnostics?metricGrid([{label:'Version / Build / Channel',value:`${data.diagnostics.version??'—'} · ${data.diagnostics.buildSha??'—'} · ${data.diagnostics.releaseChannel??'—'}`},{label:t(locale,'control.discordConnection'),value:t(locale,data.diagnostics.gatewayConnected?'control.on':'control.off')},{label:t(locale,'control.commandStatus'),value:t(locale,data.diagnostics.commandsRegistered?'control.on':'control.off')},{label:t(locale,'control.transport'),value:t(locale,data.diagnostics.transport==='gateway'?'control.gateway':'control.webhook')},{label:t(locale,'control.lastCommand'),value:data.diagnostics.lastReceivedAt?relative(data.diagnostics.lastReceivedAt):t(locale,'control.noCommand')},{label:t(locale,'control.ack'),value:data.diagnostics.lastResult?t(locale,data.diagnostics.lastResult==='success'||data.diagnostics.lastResult==='completed'?'control.ackSuccess':'control.ackFailed'):'—'},{label:t(locale,'control.ackTime'),value:data.diagnostics.lastReceivedAt&&data.diagnostics.lastAcknowledgedAt?`${Math.max(0,new Date(data.diagnostics.lastAcknowledgedAt).getTime()-new Date(data.diagnostics.lastReceivedAt).getTime())} ms`:'—'},{label:t(locale,'control.processed'),value:data.diagnostics.lastCompletedAt?relative(data.diagnostics.lastCompletedAt):'—'},{label:t(locale,'control.database'),value:t(locale,data.diagnostics.databaseConnected?'control.on':'control.off')},{label:t(locale,'control.redis'),value:t(locale,data.diagnostics.redisConnected?'control.on':'control.off')},{label:t(locale,'control.activity'),value:data.diagnostics.lastActivityAt?relative(data.diagnostics.lastActivityAt):'—'}]):callout(t(locale,'control.diagnostics'),t(locale,'control.moreData')));
 if(page==='diagnostics'&&data.diagnostics?.transport==='gateway')children.push(footer(t(locale,'control.gatewayHint')));
 if(page==='settings'&&section==='notifications'&&data.settings)children.push(footer(t(locale,'experience.queueRule',{count:data.settings.firstResponseMinutes})));
 const pageEmoji:Record<typeof controlPages[number],string>={overview:'🏠',newMembers:'👋',attention:'📥',analysis:'📊',results:'🧪',settings:'⚙️'};
 const select:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlNavigate'},true),placeholder:t(locale,'control.choosePage'),options:controlPages.map(value=>({label:t(locale,`control.${value}`),value,emoji:{name:pageEmoji[value]},default:page===value}))} satisfies APIStringSelectComponent]};
 const mainSettings=page==='settings'&&section==='main';
 const rows:ActionRow[]=page==='overview'||mainSettings?[]:[select];
 if(page==='settings'&&section==='model'&&data.model){const ja=locale==='ja',model=data.model;children.splice(1);children.push(callout(ja?'運営目的':'Community purposes',model.profile.modes.map(m=>modeNames[m][ja?0:1]).join(' · ')||(ja?'管理者が複数の目的を選べます。':'An administrator can choose multiple purposes.')));if(model.capabilities){children.push(callout(ja?'観測範囲':'Coverage',`${model.capabilities.coverage.observableChannels} / ${model.capabilities.coverage.totalRelevantChannels}\n${ja?'閲覧できないチャンネル・非公開Threadを含む全体像は未確認です。':'Unreadable channels and private threads remain partial.'}`));children.push(callout(ja?'検出された機能':'Detected capabilities',Object.entries(model.capabilities.capabilities).map(([key,entry])=>`${featureNames[key]?.[ja?0:1]??key}: ${statusNames[entry.status][ja?0:1]}`).join('\n')));}children.push(callout(ja?'用途とタグの意味':'Purposes and tag meanings',ja?'用途は管理者が指定します。Forumタグの詳しい対応付けはWeb設定で編集できます。本文・投票の意味は収集しません。':'Purposes are chosen by an administrator. Edit full Forum tag mappings in Web Settings. No body or poll meaning is collected.'));rows.push(await actionRow(issue,[{label:ja?'目的・用途を編集':'Edit purposes and mappings',action:'controlModelEdit',data:{revision:model.revision}},{label:ja?'再検出':'Rediscover',action:'controlModelRefresh'}]));}
 if(page==='overview'){const primary=await actionRow(issue,[{label:t(locale,'control.attention'),emoji:'📥',action:'controlNavigate',data:{page:'attention'},publicEntry:true,style:community?.daily.attentionCount?ButtonStyle.Primary:ButtonStyle.Secondary},{label:t(locale,'control.newMembers'),emoji:'👋',action:'controlNavigate',data:{page:'newMembers'},publicEntry:true},{label:t(locale,'control.analysis'),emoji:'📊',action:'controlNavigate',data:{page:'analysis'},publicEntry:true}]);
 try{if(data.dashboardUrl&&/^https?:$/.test(new URL(data.dashboardUrl).protocol))primary.components.push({type:ComponentType.Button,style:ButtonStyle.Link,label:data.webVerified===false?(locale==='ja'?'Web Dashboardを接続':'Connect Web Dashboard'):'Web Dashboard',emoji:{name:'🌐'},url:data.dashboardUrl});}catch{/* Invalid link omitted. */}rows.push(primary);}
 if(data.webVerified===false&&data.dashboardUrl)children.push(footer(locale==='ja'?'Web接続には、このサーバーで /nexus link を実行してください。':'Run /nexus link in this server to verify its Web connection.'));
 if(mainSettings){rows.push(await actionRow(issue,(['scope','notifications','team','goals'] as const).map((section,index)=>({label:section==='scope'?t(locale,'polish.measurement'):section==='team'?t(locale,'polish.team'):section==='goals'?t(locale,'polish.goals'):t(locale,'control.notifications'),emoji:['📏','🔔','👥','🎯'][index],action:'controlSettings',data:{section,privateSettings:true},publicEntry:true}))));}
 if(page==='overview'||mainSettings)rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue(mainSettings?{action:'controlSettings',privateSettings:true}:{action:'controlNavigate'},true),placeholder:t(locale,'polish.more'),options:(mainSettings?['summary','privacy','panel','diagnostics','advanced']:['results','settings']).map(value=>({label:t(locale,`control.${value}` as 'control.results'),value}))}]});
 if(page==='analysis')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlAnalysis'},true),placeholder:t(locale,'control.analysis'),options:analysisViews.map(value=>({label:t(locale,`control.${value}`),value,default:analysisView===value}))} satisfies APIStringSelectComponent]});
 if(page==='settings'&&!mainSettings&&data.settings){const s=data.settings;rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlSettings'},true),placeholder:t(locale,'control.chooseSetting'),options:settingsSections.filter(value=>value!=='main').map(value=>({label:t(locale,`control.${value}`),value,default:section===value}))} satisfies APIStringSelectComponent]});
  if(section==='scope')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlScope',revision:s.revision},true),placeholder:t(locale,'control.scope'),options:['all','include','exclude'].map(value=>({label:t(locale,`control.scope${value==='all'?'All':value==='include'?'Include':'Exclude'}`),value,default:s.analysisScope.mode===value}))} satisfies APIStringSelectComponent]});
  if(section==='scope'&&s.analysisScope.mode!=='all')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'controlScopeChannels',revision:s.revision},true),min_values:1,max_values:25,placeholder:t(locale,'control.chooseChannels')} satisfies APIChannelSelectComponent]});
  if(section==='team'){rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.RoleSelect,custom_id:await issue({action:'controlManagers',revision:s.revision},true),min_values:0,max_values:20,placeholder:t(locale,'control.managers')} satisfies APIRoleSelectComponent]});rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.RoleSelect,custom_id:await issue({action:'controlHelpers',revision:s.revision},true),min_values:0,max_values:20,placeholder:t(locale,'control.helpers')} satisfies APIRoleSelectComponent]});rows.push(await actionRow(issue,[{label:t(locale,'control.clearManagers'),action:'controlClearManagers',data:{revision:s.revision},publicEntry:true},{label:t(locale,'control.clearHelpers'),action:'controlClearHelpers',data:{revision:s.revision},publicEntry:true},...(!s.setupSteps?.team?[{label:t(locale,'control.noExtraRoles'),action:'controlSkipTeam',data:{revision:s.revision},publicEntry:true}]:[])]));}
  if(section==='notifications')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'controlHelperChannel',revision:s.revision},true),channel_types:[0],min_values:1,max_values:1,placeholder:t(locale,'control.destination')} satisfies APIChannelSelectComponent]});
  if(section==='notifications')rows.push(await actionRow(issue,[{label:t(locale,'polish.editConditions'),action:'controlNotificationEdit',data:{revision:s.revision,minutes:s.firstResponseMinutes,enabled:s.helperEnabled}}]));
  if(section==='goals'){
   rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlGoal',revision:s.revision},true),placeholder:t(locale,'control.chooseGoals'),min_values:0,max_values:7,options:['reply','lfg','voice','event','feedback','bug','playtest'].map(value=>({label:t(locale,`control.goal${value[0]!.toUpperCase()+value.slice(1)}` as 'control.goalReply'),value,default:s.newMemberGoals.includes(value)}))} satisfies APIStringSelectComponent]});
   if(goalPurpose!=='none')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'controlGoalChannel',purpose:goalPurpose,revision:s.revision},true),channel_types:[0],min_values:1,max_values:1,placeholder:t(locale,'control.chooseChannels')} satisfies APIChannelSelectComponent]});
  }
  if(section==='summary'){
   rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlSummaryField'},true),placeholder:t(locale,'control.chooseSummaryField'),options:['channel','day','hour','timezone'].map(value=>({label:t(locale,`control.summary${value==='channel'?'Channel':value==='day'?'Day':value==='hour'?'Hour':'Timezone'}`),value,default:summaryField===value}))} satisfies APIStringSelectComponent]});
   if(summaryField==='channel')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'controlWeeklyChannel',revision:s.revision},true),channel_types:[0],min_values:1,max_values:1,placeholder:t(locale,'control.destination')} satisfies APIChannelSelectComponent]});
   if(summaryField==='day')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlWeeklyDay',revision:s.revision},true),placeholder:t(locale,'control.day'),options:[0,1,2,3,4,5,6].map(day=>({label:t(locale,`control.day${day}` as 'control.day0'),value:String(day),default:s.weeklySummaryDay===day}))} satisfies APIStringSelectComponent]});
   if(summaryField==='hour')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlWeeklyHour',revision:s.revision},true),placeholder:t(locale,'control.time'),options:Array.from({length:24},(_,hour)=>({label:`${String(hour).padStart(2,'0')}:00`,value:String(hour),default:s.weeklySummaryHour===hour}))} satisfies APIStringSelectComponent]});
   if(summaryField==='timezone')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'controlTimezone',revision:s.revision},true),placeholder:t(locale,'control.timezone'),options:['UTC','America/Los_Angeles','America/Denver','America/Chicago','America/New_York','Europe/London','Europe/Paris','Europe/Berlin','Asia/Tokyo','Asia/Seoul','Asia/Singapore','Asia/Kolkata','Australia/Sydney'].map(value=>({label:value,value,default:s.timezone===value}))} satisfies APIStringSelectComponent]});
  }
 }
 if((page==='channels'||page==='analysis'&&analysisView==='channels')&&community?.channels.length&&community.channels.length>5)rows.push(await actionRow(issue,[{label:t(locale,'control.previous'),action:'controlChannelPage',data:{index:Math.max(0,channelPage-1)},publicEntry:true,disabled:channelPage===0},{label:t(locale,'control.next'),action:'controlChannelPage',data:{index:channelPage+1},publicEntry:true,disabled:(channelPage+1)*5>=community.channels.length}]));
 if(page==='settings'&&section==='scope'&&data.settings&&!data.settings.setupSteps?.scope)rows.push(await actionRow(issue,[{label:t(locale,'control.scopeAll'),action:'controlScopeDefault',data:{revision:data.settings.revision},publicEntry:true}]));
 if(page==='settings'&&section==='goals'&&data.settings&&!data.settings.setupSteps?.goals)rows.push(await actionRow(issue,[{label:t(locale,'control.skipGoals'),action:'controlSkipGoals',data:{revision:data.settings.revision},publicEntry:true}]));
 if(page==='settings'&&section==='panel')rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'controlMovePanel'},true),channel_types:[0],min_values:1,max_values:1,placeholder:t(locale,'control.moveHere')} satisfies APIChannelSelectComponent]});
 if(page==='settings'&&section==='diagnostics')rows.push(await actionRow(issue,[{label:t(locale,'control.openDiagnostics'),action:'controlOpenDiagnostics',publicEntry:true,emoji:'🩺'}]));
 if(page==='attention'&&community?.attention.length){const item=community.attention[Math.min(attentionIndex,community.attention.length-1)]!,total=community.daily.attentionCount??community.attention.length;rows.push(await actionRow(issue,[{label:t(locale,'control.previous'),action:'controlAttentionPage',data:{index:Math.max(0,attentionIndex-1)},publicEntry:true,disabled:attentionIndex===0},{label:t(locale,'control.acknowledge'),action:'controlAcknowledge',data:{channelId:item.channelId,messageId:item.messageId},publicEntry:true,disabled:item.status==='ACKNOWLEDGED'},{label:t(locale,'control.snooze'),action:'controlSnoozeMenu',data:{channelId:item.channelId,messageId:item.messageId},publicEntry:true},{label:t(locale,'control.resolve'),action:'controlResolve',data:{channelId:item.channelId,messageId:item.messageId},publicEntry:true,emoji:'✅'},{label:t(locale,'control.next'),action:'controlAttentionPage',data:{index:attentionIndex+1},publicEntry:true,disabled:attentionIndex+1>=total||attentionIndex>=1000}]));}
 if(page==='overview'&&data.settings?.setupVersion===1)rows.push(await actionRow(issue,[{label:t(locale,'control.reviewSetup'),action:'controlReviewSetup',publicEntry:true},{label:t(locale,'control.keepSettings'),action:'controlKeepSettings',data:{revision:data.settings.revision},publicEntry:true}]));
 if(page==='settings'&&section==='notifications'&&data.settings)rows.push(await actionRow(issue,[{label:t(locale,data.settings.helperEnabled?'helper.disable':'helper.enable'),action:'controlHelperToggle',data:{revision:data.settings.revision,value:!data.settings.helperEnabled},publicEntry:true},{label:t(locale,'control.testAlert'),action:'controlTestAlert',publicEntry:true},...(!data.settings.setupSteps?.notifications?[{label:t(locale,'control.skipNotifications'),action:'controlSkipNotifications',data:{revision:data.settings.revision},publicEntry:true}]:[])]));
 if(page==='settings'&&section==='summary'&&data.settings)rows.push(await actionRow(issue,[{label:t(locale,data.settings.weeklySummaryEnabled?'control.disable':'control.enable'),action:'controlWeeklyToggle',data:{revision:data.settings.revision,value:!data.settings.weeklySummaryEnabled},publicEntry:true},{label:t(locale,'control.testSummary'),action:'controlTestSummary',publicEntry:true}]));
 if(page==='settings'&&section==='privacy')rows.push(await actionRow(issue,[{label:t(locale,'control.details'),action:'privacy',publicEntry:true}]));
 if(page==='settings'&&section==='advanced')rows.push(await actionRow(issue,[{label:t(locale,'control.advanced'),action:'advanced',publicEntry:true}]));
 if(page==='analysis'&&community?.suggestion?.key==='reply_rescue')rows.push(await actionRow(issue,[{label:t(locale,'control.tryImprovement'),action:'controlTryImprove',publicEntry:true,style:ButtonStyle.Primary}]));
 if(page==='overview'){
  const actions:ButtonSpec[]=[{label:t(locale,'polish.rules'),action:'controlRules',publicEntry:true},...(community?.suggestion?.key==='reply_rescue'?[{label:t(locale,'polish.evidence'),action:'controlNavigate',data:{page:'analysis'},publicEntry:true},{label:t(locale,'control.tryImprovement'),action:'controlTryImprove',publicEntry:true,style:ButtonStyle.Primary as const}]:[])];
  actions.push({label:`↻ ${t(locale,'control.refresh')}`,action:'controlRefresh',data:{page,section,channelPage},publicEntry:true});
  rows.push(await actionRow(issue,actions));
 }
 if(page==='settings'&&data.settings&&['scope','team','notifications','goals'].includes(section)&&data.settings.setupSteps&&!Object.values(data.settings.setupSteps).every(Boolean)){
  const steps=['scope','team','notifications','goals'],number=steps.indexOf(section)+1;
  children.unshift(callout(locale==='ja'?`セットアップ ${number}/4`:`Setup ${number}/4`,t(locale,`control.${section}`)));
  const wizard=await actionRow(issue,[{label:locale==='ja'?'完了して次へ':'Complete and continue',action:'setupNext',data:{step:section,revision:data.settings.revision,mode:'complete'},style:ButtonStyle.Primary},{label:locale==='ja'?'スキップして次へ':'Skip and continue',action:'setupNext',data:{step:section,revision:data.settings.revision,mode:'skip'}}]);
  if(rows.length>=5){const last=rows[rows.length-1]!;if(last.components.every(component=>component.type===ComponentType.Button)&&last.components.length+wizard.components.length<=5)(last.components as APIButtonComponent[]).push(...wizard.components as APIButtonComponent[]);else{rows.pop();rows.push(wizard);}}
  else rows.push(wizard);
 }
 if(page!=='settings'&&page!=='overview'||mainSettings){
  const buttons=await actionRow(issue,[...(mainSettings?[{label:t(locale,'control.overview'),action:'controlNavigate',data:{page:'overview'},publicEntry:true,emoji:'🏠'}]:[]),{label:`↻ ${t(locale,'control.refresh')}`,action:'controlRefresh',data:{page,section,channelPage},publicEntry:true,style:ButtonStyle.Secondary}]);
  try{if(data.dashboardUrl&&/^https?:$/.test(new URL(data.dashboardUrl).protocol))buttons.components.push({type:ComponentType.Button,style:ButtonStyle.Link,label:t(locale,'control.openWeb'),url:data.dashboardUrl} satisfies APIButtonComponent);}catch{/* No link when the URL is invalid. */}
  rows.push(buttons);
 }
 children.push(footer(t(locale,'control.updated',{time:`<t:${Math.floor((data.updatedAt??new Date()).getTime()/1000)}:R>`})));
 return nexusPanel({title:page==='overview'?`NEXUS · ${t(locale,'experience.homeTitle')}`:page==='settings'?t(locale,'polish.settingsTitle'):t(locale,'control.title'),subtitle:`${t(locale,`control.${page}`)} · ${t(locale,'control.subtitle')}`,children,rows});
}
