import {ButtonStyle} from 'discord-api-types/v10';
import {discordLabel,t,type MessageKey,type UiLocale} from '../i18n/index.js';
import {actionRow,callout,divider,footer,nexusPanel,type Panel} from '../primitives.js';
import type {Issue} from '../types.js';
export type ErrorKind='revision'|'permission'|'entitlement'|'generic';
export async function errorPanel(issue:Issue,kind:ErrorKind='generic',locale:UiLocale='en',reference?:string,code?:string):Promise<Panel>{
 if(code==='CHANNEL_PERMISSION_MISSING'||code==='INVALID_START_CHANNEL')return nexusPanel({title:locale==='ja'?'この改善策を有効にできません':'Cannot enable this improvement',subtitle:locale==='ja'?'通知先を確認してください':'Check the notification destination',accent:'critical',children:[divider(),callout(locale==='ja'?'何が起きたか':'What happened',locale==='ja'?'NEXUS は選択したチャンネルに送信できません。別のチャンネルを選ぶか、表示・送信権限を確認してください。':'NEXUS cannot send messages in the selected channel. Choose another channel or grant View and Send permissions.'),...(reference?[callout(t(locale,'error.ref'),`**${reference}**`)]:[])],rows:[await actionRow(issue,[{label:locale==='ja'?'別のチャンネルを選ぶ':'Choose another channel',action:'interventions',style:ButtonStyle.Primary},{label:locale==='ja'?'権限を確認':'Check permissions',action:'status'}])]});
 if(code==='EVENT_NOT_AVAILABLE')return nexusPanel({title:locale==='ja'?'イベントが見つかりません':'Event no longer available',subtitle:locale==='ja'?'利用できるイベントを選び直してください':'Choose an available event',accent:'critical',children:[divider(),...(reference?[callout(t(locale,'error.ref'),`**${reference}**`)]:[])],rows:[await actionRow(issue,[{label:locale==='ja'?'改善に戻る':'Back to Improve',action:'improve',style:ButtonStyle.Primary}])]});
 if(code==='HELPER_CHANNEL_REQUIRED')return nexusPanel({title:t(locale,'helper.title'),subtitle:t(locale,'helper.needChannel'),accent:'critical',children:[divider()],rows:[await actionRow(issue,[{label:t(locale,'control.openSettings'),action:'settings',style:ButtonStyle.Primary}])]});
 if(code==='COMPONENT_EXPIRED'||code==='PANEL_NOT_CONFIGURED')return nexusPanel({title:locale==='ja'?'このパネルは古くなりました':'This panel is out of date',subtitle:locale==='ja'?'現在のパネルを開いて操作してください':'Open the current panel and try again',accent:'critical',children:[divider()],rows:[await actionRow(issue,[{label:discordLabel(locale,'error.openPanel'),action:'panel',style:ButtonStyle.Primary}])]});
 const keys:Record<ErrorKind,[MessageKey,MessageKey]>={revision:['error.revisionTitle','error.revisionDetail'],permission:['error.permissionTitle','error.permissionDetail'],entitlement:['error.entitlementTitle','error.entitlementDetail'],generic:['error.genericTitle','error.genericSubtitle']},[title,subtitle]=keys[kind];
 return nexusPanel({title:t(locale,title),subtitle:t(locale,subtitle),accent:'critical',children:[divider(),...(kind==='generic'?[callout(t(locale,'error.possible'),t(locale,'error.causes'))]:[]),callout(t(locale,'error.safe'),kind==='generic'?t(locale,'error.unknownState'):t(locale,'error.notCommitted')),...(reference?[callout(t(locale,'error.ref'),`**${reference}**`)]:[]),footer(t(locale,'error.footer'))],rows:[await actionRow(issue,[{label:discordLabel(locale,'error.openPanel'),action:'panel',style:ButtonStyle.Primary},{label:discordLabel(locale,'error.runDiagnostics'),action:'status'},{label:discordLabel(locale,'common.back'),action:'settings'}])]});
}
