import {ButtonStyle,ComponentType,type APIChannelSelectComponent,type APIStringSelectComponent} from 'discord-api-types/v10';
import {shortId} from '../formatting.js';
import {discordLabel,t,type UiLocale} from '../i18n/index.js';
import {actionRow,callout,divider,emptyState,footer,nexusPanel,section,type ActionRow,type Panel} from '../primitives.js';
import {interventionStateLabel} from '../status.js';
import type {Issue} from '../types.js';
export type InterventionRunView={id:string;state:string};
export async function interventionsPanel(issue:Issue,runs:InterventionRunView[],locale:UiLocale='en'):Promise<Panel>{const pending=runs.filter(r=>r.state==='suggested'||r.state==='approval'),rows:ActionRow[]=[];if(pending.length)rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'interventionApprove'}),placeholder:discordLabel(locale,'interventions.approve',{},150),options:pending.slice(0,25).map(r=>({label:`${interventionStateLabel(r.state,locale)} · ${shortId(r.id)}`.slice(0,100),value:r.id,description:t(locale,'interventions.helper').slice(0,100)}))} satisfies APIStringSelectComponent]});rows.push({type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'interventionDraft'}),placeholder:discordLabel(locale,'interventions.channel',{},150),channel_types:[0],min_values:1,max_values:1} satisfies APIChannelSelectComponent]});const recent=runs.length?section(t(locale,'interventions.recent'),runs.slice(0,10).map(r=>`**${t(locale,'interventions.helper')}**\n${interventionStateLabel(r.state,locale)}\n-# ${t(locale,'interventions.reference',{id:shortId(r.id)})}`).join('\n\n')):emptyState(t(locale,'interventions.none'),t(locale,'interventions.noneDetail'));return nexusPanel({title:t(locale,'area.actions'),subtitle:t(locale,'area.actionsSubtitle'),accent:pending.length?'warning':'nexus',children:[divider(),recent,divider(),callout(t(locale,'interventions.new'),`**${t(locale,'interventions.mode')}**\n${t(locale,'interventions.suggest')}\n\n**${t(locale,'interventions.trigger')}**\n${t(locale,'interventions.after24')}\n\n**${t(locale,'interventions.action')}**\n${t(locale,'interventions.alertStaff')}\n\n**${t(locale,'interventions.safety')}**\n${t(locale,'interventions.limits')}`),footer(t(locale,'interventions.footer'))],rows:[...rows,await actionRow(issue,[{label:discordLabel(locale,'root.viewResults'),action:'experiments',style:ButtonStyle.Primary},{label:discordLabel(locale,'root.viewOpportunity'),action:'diagnose'}])]});}
export async function interventionPreviewPanel(issue:Issue,publishData:Record<string,unknown>,locale:UiLocale='en'):Promise<Panel>{return nexusPanel({title:t(locale,'interventions.preview'),subtitle:t(locale,'interventions.previewSubtitle'),children:[divider(),callout(t(locale,'interventions.mode'),t(locale,'interventions.suggest')),callout(t(locale,'interventions.trigger'),t(locale,'interventions.after24')),callout(t(locale,'interventions.action'),t(locale,'interventions.selectedChannel')),callout(t(locale,'interventions.safety'),t(locale,'interventions.safetyDetail'))],rows:[await actionRow(issue,[{label:discordLabel(locale,'interventions.publish'),action:'configPublish',data:publishData,style:ButtonStyle.Primary},{label:discordLabel(locale,'common.back'),action:'interventions'}])]});}
