import {ButtonStyle,ComponentType,type APIRoleSelectComponent,type APIStringSelectComponent} from 'discord-api-types/v10';
import {actionRow,callout,divider,emptyState,footer,nexusPanel,type ActionRow,type Panel} from '../primitives.js';
import type {Issue} from '../types.js';

export async function rolloutPreviewPanel(issue:Issue,revision:number):Promise<Panel>{return nexusPanel({title:'Preview Platform Rollout',subtitle:'Enable the activation and experimentation toolchain',children:[divider(),callout('Capabilities','Native capability reads · Native checkpoints · Activation definitions · Interventions · Experiments'),callout('What stays unchanged','Existing fallback mode is preserved. Published definitions and plan entitlements are still required.')],rows:[await actionRow(issue,[{label:'Confirm rollout',action:'rolloutConfirm',data:{revision},style:ButtonStyle.Primary},{label:'Back',action:'setup'}])]});}

export async function onboardingModePreviewPanel(issue:Issue,view:{from:string;to:string;publishData:Record<string,unknown>}):Promise<Panel>{return nexusPanel({title:'Preview NEXUS Mode',subtitle:`${view.from} → ${view.to}`,children:[divider(),callout('Discord remains unchanged',"NEXUS will not modify Discord's Native Onboarding configuration."),...(view.to==='hybrid'?[callout('Hybrid requirement','Configure an explicit additional NEXUS flow before enabling Hybrid mode.')]:[])],rows:[await actionRow(issue,[{label:'Publish mode',action:'configPublish',data:view.publishData,style:ButtonStyle.Primary},{label:'Back',action:'setup'}])]});}

export async function onboardingNotConfiguredPanel(issue:Issue):Promise<Panel>{return nexusPanel({title:'NEXUS · Onboarding',subtitle:'A template is required first',accent:'collecting',children:[divider(),emptyState('Choose a community template','Settings uses the template to create the first versioned onboarding flow.')],rows:[await actionRow(issue,[{label:'Open Settings',action:'settings',style:ButtonStyle.Primary}])]});}

export async function onboardingFlowPanel(issue:Issue,view:{revision:number;nodes:Array<{id:string;question:string;options:Array<{id:string;label:string}>}>;versions:Array<{id:string;version:number}>}):Promise<Panel>{
 const optionSelect:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'mapOption',revision:view.revision}),placeholder:'Choose an answer to map a role',options:view.nodes.flatMap(node=>node.options.map(option=>({label:`${node.id}: ${option.label}`.slice(0,100),value:`${node.id}:${option.id}`}))).slice(0,25)} satisfies APIStringSelectComponent]};
 const rollback:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'rollback',revision:view.revision}),placeholder:'Publish a copy of an earlier version',options:view.versions.map(version=>({label:`Version ${version.version}`,value:version.id}))} satisfies APIStringSelectComponent]};
 const edit:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'editNode',revision:view.revision}),placeholder:'Edit a question and its options',options:view.nodes.map(node=>({label:node.question.slice(0,100),value:node.id}))} satisfies APIStringSelectComponent]};
 return nexusPanel({title:'NEXUS · Onboarding Flow',subtitle:'Immutable, versioned member journeys',children:[divider(),callout('Version behavior','Mapping a role, editing a question, or rolling back publishes a new version. Existing sessions keep the version they started with.'),footer('Role mappings are limited to roles below the NEXUS bot role.')],rows:[optionSelect,rollback,edit,await actionRow(issue,[{label:'Settings',action:'settings'}])]});
}

export async function editQuestionPanel(issue:Issue,view:{revision:number;nodeId:string;question:string;options:string}):Promise<Panel>{return nexusPanel({title:'Edit Onboarding Question',subtitle:'A new flow version will be published',children:[divider(),callout('Current question',view.question),footer('Members already in progress remain on their original version.')],rows:[await actionRow(issue,[{label:'Open editor',action:'editNodeOpen',data:view,style:ButtonStyle.Primary},{label:'Back',action:'flows'}])]});}

export async function roleMappingPanel(issue:Issue,view:{revision:number;option:string}):Promise<Panel>{const select:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.RoleSelect,custom_id:await issue({action:'mapRole',revision:view.revision,option:view.option}),min_values:0,max_values:1} satisfies APIRoleSelectComponent]};return nexusPanel({title:'NEXUS · Managed Role Mapping',subtitle:'Connect an onboarding answer to a community role',children:[divider(),callout('Safety boundary','Choose a role below the NEXUS bot role. Privileged roles cannot be mapped.')],rows:[select,await actionRow(issue,[{label:'Back',action:'flows'}])]});}

export async function sessionCompletePanel(issue:Issue):Promise<Panel>{return nexusPanel({title:'Your Community Setup',subtitle:'Preferences saved',accent:'healthy',children:[divider(),callout('Role changes','Eligible role changes are queued. You can update your preferences at any time.')],rows:[await actionRow(issue,[{label:'Update Preferences / Restart Setup',action:'restart',style:ButtonStyle.Primary},{label:'Privacy',action:'privacy'}])]});}
