import {ButtonStyle,ComponentType,type APIRoleSelectComponent,type APIStringSelectComponent} from 'discord-api-types/v10';
import {discordLabel,t,type UiLocale} from '../i18n/index.js';
import {actionRow,callout,divider,emptyState,footer,nexusPanel,type ActionRow,type Panel} from '../primitives.js';
import type {Issue} from '../types.js';
export async function rolloutPreviewPanel(issue:Issue,revision:number,locale:UiLocale='en'):Promise<Panel>{return nexusPanel({title:t(locale,'onboarding.rolloutPreview'),subtitle:t(locale,'onboarding.rolloutSubtitle'),children:[divider(),callout(t(locale,'onboarding.capabilities'),t(locale,'onboarding.capabilitiesDetail')),callout(t(locale,'onboarding.unchanged'),t(locale,'onboarding.unchangedDetail'))],rows:[await actionRow(issue,[{label:discordLabel(locale,'onboarding.confirmRollout'),action:'rolloutConfirm',data:{revision},style:ButtonStyle.Primary},{label:discordLabel(locale,'common.back'),action:'setup'}])]});}
export async function onboardingModePreviewPanel(issue:Issue,view:{from:string;to:string;publishData:Record<string,unknown>},locale:UiLocale='en'):Promise<Panel>{const mode=(value:string)=>t(locale,value==='auto'?'mode.auto':value==='native'?'mode.native':value==='fallback'?'mode.fallback':'mode.hybrid');return nexusPanel({title:t(locale,'onboarding.modePreview'),subtitle:`${mode(view.from)} → ${mode(view.to)}`,children:[divider(),callout(t(locale,'onboarding.discordUnchanged'),t(locale,'readiness.discordDetail')),...(view.to==='hybrid'?[callout(t(locale,'onboarding.hybrid'),t(locale,'onboarding.hybridDetail'))]:[])],rows:[await actionRow(issue,[{label:discordLabel(locale,'onboarding.publishMode'),action:'configPublish',data:view.publishData,style:ButtonStyle.Primary},{label:discordLabel(locale,'common.back'),action:'setup'}])]});}
export async function onboardingNotConfiguredPanel(issue:Issue,locale:UiLocale='en'):Promise<Panel>{return nexusPanel({title:t(locale,'onboarding.title'),subtitle:t(locale,'onboarding.templateRequired'),accent:'collecting',children:[divider(),emptyState(t(locale,'onboarding.chooseTemplate'),t(locale,'onboarding.chooseTemplateDetail'))],rows:[await actionRow(issue,[{label:discordLabel(locale,'onboarding.openSettings'),action:'settings',style:ButtonStyle.Primary}])]});}
export async function onboardingFlowPanel(issue:Issue,view:{revision:number;nodes:Array<{id:string;question:string;options:Array<{id:string;label:string}>}>;versions:Array<{id:string;version:number}>},locale:UiLocale='en'):Promise<Panel>{const optionSelect:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'mapOption',revision:view.revision}),placeholder:discordLabel(locale,'onboarding.mapRole',{},150),options:view.nodes.flatMap(node=>node.options.map(option=>({label:`${node.id}: ${option.label}`.slice(0,100),value:`${node.id}:${option.id}`}))).slice(0,25)} satisfies APIStringSelectComponent]},rollback:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'rollback',revision:view.revision}),placeholder:discordLabel(locale,'onboarding.rollback',{},150),options:view.versions.map(version=>({label:t(locale,'onboarding.versionOption',{version:version.version}).slice(0,100),value:version.id}))} satisfies APIStringSelectComponent]},edit:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'editNode',revision:view.revision}),placeholder:discordLabel(locale,'onboarding.edit',{},150),options:view.nodes.map(node=>({label:node.question.slice(0,100),value:node.id}))} satisfies APIStringSelectComponent]};return nexusPanel({title:t(locale,'onboarding.flowTitle'),subtitle:t(locale,'onboarding.flowSubtitle'),children:[divider(),callout(t(locale,'onboarding.versionBehavior'),t(locale,'onboarding.versionDetail')),footer(t(locale,'onboarding.roleFooter'))],rows:[optionSelect,rollback,edit,await actionRow(issue,[{label:discordLabel(locale,'common.settings'),action:'settings'}])]});}
export async function editQuestionPanel(issue:Issue,view:{revision:number;nodeId:string;question:string;options:string},locale:UiLocale='en'):Promise<Panel>{return nexusPanel({title:t(locale,'onboarding.editTitle'),subtitle:t(locale,'onboarding.newVersion'),children:[divider(),callout(t(locale,'onboarding.currentQuestion'),view.question),footer(t(locale,'onboarding.memberVersion'))],rows:[await actionRow(issue,[{label:discordLabel(locale,'onboarding.openEditor'),action:'editNodeOpen',data:view,style:ButtonStyle.Primary},{label:discordLabel(locale,'common.back'),action:'flows'}])]});}
export async function roleMappingPanel(issue:Issue,view:{revision:number;option:string},locale:UiLocale='en'):Promise<Panel>{const select:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.RoleSelect,custom_id:await issue({action:'mapRole',revision:view.revision,option:view.option}),min_values:0,max_values:1} satisfies APIRoleSelectComponent]};return nexusPanel({title:t(locale,'onboarding.roleTitle'),subtitle:t(locale,'onboarding.roleSubtitle'),children:[divider(),callout(t(locale,'onboarding.safety'),t(locale,'onboarding.safetyDetail'))],rows:[select,await actionRow(issue,[{label:discordLabel(locale,'common.back'),action:'flows'}])]});}
export async function sessionCompletePanel(issue:Issue,locale:UiLocale='en'):Promise<Panel>{return nexusPanel({title:t(locale,'onboarding.setupTitle'),subtitle:t(locale,'onboarding.saved'),accent:'healthy',children:[divider(),callout(t(locale,'onboarding.roleChanges'),t(locale,'onboarding.roleChangesDetail'))],rows:[await actionRow(issue,[{label:discordLabel(locale,'onboarding.update'),action:'restart',style:ButtonStyle.Primary},{label:discordLabel(locale,'common.privacy'),action:'privacy'}])]});}
