import {ButtonStyle,ComponentType,type APIChannelSelectComponent,type APIStringSelectComponent} from 'discord-api-types/v10';
import {discordLabel,t,type UiLanguage,type UiLocale} from '../i18n/index.js';
import {actionRow,callout,divider,footer,metricGrid,nexusPanel,type ActionRow,type Panel} from '../primitives.js';
import type {Issue} from '../types.js';
export type SettingsView={enabled:boolean;onboardingEnabled:boolean;template:string;startChannelId:string|null;revision:number;uiLanguage?:UiLanguage};
export async function settingsPanel(issue:Issue,settings:SettingsView,locale:UiLocale='en'):Promise<Panel>{
 const revision=settings.revision,uiLanguage=settings.uiLanguage??'auto';
 const templateKeys={'Gaming':'settings.templateGaming','Creator':'settings.templateCreator','Developer / OSS':'settings.templateDeveloper','Product / SaaS':'settings.templateProduct','Education':'settings.templateEducation','General Community':'settings.templateGeneral'} as const;
 const template:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'template',revision}),placeholder:discordLabel(locale,'settings.chooseTemplate',{},150),options:Object.entries(templateKeys).map(([value,key])=>({label:t(locale,key).slice(0,100),value,default:value===settings.template}))} satisfies APIStringSelectComponent]};
 const channel:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'startChannel',revision}),channel_types:[0],placeholder:discordLabel(locale,'settings.chooseChannel',{},150),min_values:1,max_values:1} satisfies APIChannelSelectComponent]};
 const language:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'uiLanguage',revision}),placeholder:discordLabel(locale,'settings.chooseLanguage',{},150),options:[{label:t(locale,'settings.auto'),value:'auto'},{label:t(locale,'settings.japanese'),value:'ja'},{label:t(locale,'settings.english'),value:'en'},{label:t(locale,'settings.bilingual'),value:'bilingual'}].map(option=>({...option,label:option.label.slice(0,100),default:option.value===uiLanguage}))} satisfies APIStringSelectComponent]};
 return nexusPanel({title:t(locale,'settings.title'),subtitle:t(locale,'settings.revision',{revision}),accent:settings.enabled?'healthy':'neutral',children:[divider(),metricGrid([{label:t(locale,'settings.nexus'),value:settings.enabled?t(locale,'common.enabled'):t(locale,'common.disabled')},{label:t(locale,'settings.onboarding'),value:settings.onboardingEnabled?t(locale,'common.enabled'):t(locale,'common.disabled')},{label:t(locale,'settings.template'),value:t(locale,templateKeys[settings.template as keyof typeof templateKeys]??'settings.templateGeneral')},{label:t(locale,'settings.startChannel'),value:settings.startChannelId?`<#${settings.startChannelId}>`:t(locale,'common.notConfigured')},{label:t(locale,'settings.language'),value:t(locale,uiLanguage==='auto'?'settings.auto':uiLanguage==='ja'?'settings.japanese':uiLanguage==='en'?'settings.english':'settings.bilingual')}]),divider(),callout(t(locale,'settings.automation'),t(locale,'settings.suggest')),footer(t(locale,'settings.footer'))],rows:[template,channel,language,await actionRow(issue,[{label:discordLabel(locale,settings.enabled?'settings.disableNexus':'settings.enableNexus'),action:'enabled',data:{revision,value:!settings.enabled},style:settings.enabled?ButtonStyle.Danger:ButtonStyle.Primary},{label:discordLabel(locale,settings.onboardingEnabled?'settings.disableOnboarding':'settings.enableOnboarding'),action:'onboardingEnabled',data:{revision,value:!settings.onboardingEnabled}}]),await actionRow(issue,[{label:discordLabel(locale,'settings.roleMappings'),action:'flows'},{label:discordLabel(locale,'settings.preview'),action:'preview'},{label:discordLabel(locale,'common.privacy'),action:'privacy'}])]});
}
