import {ButtonStyle,ComponentType,type APIChannelSelectComponent,type APIStringSelectComponent} from 'discord-api-types/v10';
import {actionRow,callout,divider,footer,metricGrid,nexusPanel,type ActionRow,type Panel} from '../primitives.js';
import type {Issue} from '../types.js';
export type SettingsView={enabled:boolean;onboardingEnabled:boolean;template:string;startChannelId:string|null;revision:number};
export async function settingsPanel(issue:Issue,settings:SettingsView):Promise<Panel>{
 const revision=settings.revision;
 const template:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.StringSelect,custom_id:await issue({action:'template',revision}),placeholder:'Choose community template',options:['Gaming','Creator','Developer / OSS','Product / SaaS','Education','General Community'].map(label=>({label,value:label,default:label===settings.template}))} satisfies APIStringSelectComponent]};
 const channel:ActionRow={type:ComponentType.ActionRow,components:[{type:ComponentType.ChannelSelect,custom_id:await issue({action:'startChannel',revision}),channel_types:[0],placeholder:'Choose a start channel',min_values:1,max_values:1} satisfies APIChannelSelectComponent]};
 return nexusPanel({title:'NEXUS · Community Settings',subtitle:`Configuration revision ${revision}`,accent:settings.enabled?'healthy':'neutral',children:[divider(),metricGrid([{label:'NEXUS',value:settings.enabled?'Enabled':'Disabled'},{label:'Onboarding',value:settings.onboardingEnabled?'Enabled':'Disabled'},{label:'Template',value:settings.template},{label:'Start channel',value:settings.startChannelId?`<#${settings.startChannelId}>`:'Not configured'}]),divider(),callout('Automation mode','Suggest · automated actions require explicit approval.'),footer('Changes are revision-safe. Stale controls are rejected rather than overwriting newer settings.')],rows:[template,channel,await actionRow(issue,[{label:settings.enabled?'Disable NEXUS':'Enable NEXUS',action:'enabled',data:{revision,value:!settings.enabled},style:settings.enabled?ButtonStyle.Danger:ButtonStyle.Primary},{label:settings.onboardingEnabled?'Disable onboarding':'Enable onboarding',action:'onboardingEnabled',data:{revision,value:!settings.onboardingEnabled}}]),await actionRow(issue,[{label:'Role mappings',action:'flows'},{label:'Preview',action:'preview'},{label:'Privacy',action:'privacy'}])]});
}
