import {ComponentType} from 'discord-api-types/v10';
import {describe,expect,it} from 'vitest';
import {coverageLabel,controlPanel,controlPages,diagnosticsPanel,errorPanel,experimentsPanel,experimentMethodPanel,formatDuration,formatPercentage,guidedSetupPanel,improvePanel,lifecyclePanel,overviewPanel,resolveLocale,rootPanel,settingsPanel,type MetricLike,type Panel} from '../../packages/discord-panels/src/index.js';
import {en,ja} from '../../packages/discord-panels/src/i18n/index.js';
import {buildNexusCommand} from '../../scripts/commands.js';

let counter=0;const issue=async()=>`opaque-${counter++}`;
const metric=(metricKey:string,value:number|null,sampleSize=12,status:MetricLike['dataCoverage']['status']='healthy'):MetricLike=>({metricKey,value,sampleSize,provisional:false,dataCoverage:{status,expected:100,observed:status==='healthy'?100:63}});
const metrics=()=>({
 new_members:metric('new_members',12),activation_rate:metric('activation_rate',.583),direct_reply_connection_rate:metric('direct_reply_connection_rate',.67),d7_active_retention:metric('d7_active_retention',.31),
 onboarding_completion:metric('onboarding_completion',.74),ttfv_median:metric('ttfv_median',1080),median_first_reply_latency:metric('median_first_reply_latency',523),d1_active_retention:metric('d1_active_retention',.54),d30_active_retention:metric('d30_active_retention',null,0)
});
const experiment=(evidenceStatus:string)=>({name:'Helper alert vs holdout',primaryMetric:'activation',minimumSample:20,windowSeconds:604800,result:{controlN:24,treatmentN:25,controlRate:.4,treatmentRate:.56,absoluteLift:.16,evidenceStatus,credibleInterval:evidenceStatus==='SUPPORTED'?[.02,.3]:null,probabilityTreatmentBetter:evidenceStatus==='SUPPORTED'?.98:null,dataCoverage:'healthy',coverageRatio:1,assigned:49,mature:49,provisional:false,guardrails:{leaveRate:.04,deliveryFailureRate:.02,alertVolume:25},randomization:'time_block',state:'running'}});
const json=(panel:Panel)=>JSON.stringify(panel);

describe('NEXUS Discord design system',()=>{
 it('formats percentages for people',()=>{expect(formatPercentage(.583)).toBe('58%');expect(formatPercentage(.583,1)).toBe('58.3%');});
 it('formats durations compactly',()=>{expect(formatDuration(523)).toBe('8m 43s');expect(formatDuration(3660)).toBe('1h 1m');});
 it('does not turn a zero sample into a zero metric',async()=>{const panel=await lifecyclePanel(issue,{...metrics(),activation_rate:metric('activation_rate',null,0)});expect(json(panel)).toContain('Not available yet');expect(json(panel)).not.toContain('**0%**');});
 it('explains an unavailable retention metric',async()=>{const panel=await lifecyclePanel(issue,metrics());expect(json(panel)).toContain('D30 is not complete yet');});
 it('formats partial data collection',()=>{expect(coverageLabel('degraded',.63)).toBe('Some data could not be collected · 63%');});
 it('formats healthy data collection without redundant percentage',()=>{expect(coverageLabel('healthy',1)).toBe('Data collected normally');});
 it('renders the overview empty state without an unavailable wall',async()=>{const panel=await overviewPanel(issue,{new_members:metric('new_members',0,0)});expect(json(panel)).toContain('COLLECTING DATA');expect(json(panel)).toContain('Track the first newcomer');expect(json(panel).match(/Not available/g)?.length??0).toBe(0);});
 it('renders four populated overview KPIs',async()=>{const panel=await overviewPanel(issue,metrics());for(const label of ['Successful newcomers','New Members','First Reply','Active after 7 days'])expect(json(panel)).toContain(label);expect(json(panel)).toContain('58%');});
 it('separates community attention from data collection status',async()=>{const panel=await overviewPanel(issue,{...metrics(),d7_active_retention:metric('d7_active_retention',.31,12,'degraded')},'en',{diagnosis:{type:'ACTIVATION_DROP',severity:'warning'},unansweredAfter24h:3});const value=json(panel);expect(value).toContain('First success dropped');expect(value).toContain('Data collection status');expect(value).toContain('1 primary signals');});
 it('groups lifecycle metrics by independent milestone',async()=>{const panel=await lifecyclePanel(issue,metrics());for(const stage of ['Joined','Completed joining steps','Reached first success','Received a reply','Active later'])expect(json(panel)).toContain(`### ${stage}`);});
 it('translates diagnosis enums and shows comparison',async()=>{const panel=await diagnosticsPanel(issue,[{type:'ACTIVATION_DROP',severity:'warning',comparison:{current:.41,baseline:.56},facts:{},sampleSize:30,confidenceLabel:'observational'}]);expect(json(panel)).toContain('First success dropped');expect(json(panel)).toContain('−15 percentage points');expect(json(panel)).not.toContain('ACTIVATION_DROP');});
 it('renders insufficient experiment evidence in plain language',async()=>{const panel=await experimentsPanel(issue,experiment('INSUFFICIENT_DATA'));expect(json(panel)).toContain('Not enough data');expect(json(panel)).not.toContain('INSUFFICIENT_DATA');});
 it('keeps comparison method details behind a separate view',async()=>{const panel=await experimentsPanel(issue,experiment('SUPPORTED')),advanced=await experimentMethodPanel(issue,experiment('SUPPORTED'));expect(json(panel)).toContain('Current results support the improvement');expect(json(panel)).not.toContain('Randomized');expect(json(advanced)).toContain('People may interact across time blocks');});
 it('renders a guardrail breach as a stopped safety state',async()=>{const panel=await experimentsPanel(issue,experiment('GUARDRAIL_BREACH'));expect(json(panel)).toContain('Stopped for safety');expect(json(panel)).toContain('stopped this check for safety');});
 it('renders a standardized safe error panel',async()=>{const panel=await errorPanel(issue,'generic','en','NXS-A1B2C3');expect(json(panel)).toContain("Action couldn't be completed");expect(json(panel)).toContain('final state could not be confirmed');expect(json(panel)).toContain('NXS-A1B2C3');expect(json(panel)).toContain('Open Panel');expect(json(panel)).not.toContain('No configuration change was committed');expect(json(panel)).not.toMatch(/stack|token|database error/i);});
 it('renders English Overview',async()=>{expect(json(await overviewPanel(issue,metrics(),'en'))).toContain('Community Overview');});
 it('renders Japanese Overview and formatting',async()=>{const value=json(await overviewPanel(issue,metrics(),'ja'));expect(value).toContain('コミュニティ概要');expect(value).toContain('新規メンバー');expect(formatDuration(523,'ja')).toBe('8分43秒');});
 it('renders bilingual Overview with compact canonical labels',async()=>{const value=json(await overviewPanel(issue,metrics(),'bilingual'));expect(value).toContain('コミュニティ概要 / NEXUS · Community Overview');expect(value).toContain('成功した新規メンバー / Successful newcomers');});
 it('resolves locale fallback for user and public panels',()=>{expect(resolveLocale('auto',{interactionLocale:'ja',guildLocale:'en-US'})).toBe('ja');expect(resolveLocale('auto',{interactionLocale:'ja',guildLocale:'en-US',publicPanel:true})).toBe('en');expect(resolveLocale('auto',{})).toBe('en');});
 it.each([['SETUP_REQUIRED','Choose what a successful newcomer'],['COLLECTING_DATA','Collecting newcomer activity'],['HEALTHY','Data is being collected normally'],['NEEDS_ATTENTION','Needs attention'],['EXPERIMENT_RUNNING','Checking whether an improvement helped']] as const)('renders permanent panel state %s with refresh and update time',async(state,label)=>{const value=json(await rootPanel(issue,'en',{state,activation:metrics().activation_rate,connection:metrics().direct_reply_connection_rate,retention:metrics().d7_active_retention,attention:'First replies are taking longer',suggestedAction:'Reply Rescue',setupRemaining:3,updatedAt:new Date('2026-01-01T00:00:00Z')}));expect(value).toContain(label);expect(value).toContain('Refresh');expect(value).toContain('Updated');expect(value).toContain('1767225600');});
 it('localizes the guided permanent panel and never renders a broken dashboard fallback',async()=>{const value=json(await rootPanel(issue,'ja',{state:'NEEDS_ATTENTION',attention:'返信が遅くなっています',suggestedAction:'返信レスキュー'}));expect(value).toContain('今見るべきこと');expect(value).not.toContain('dashboard"');});
 it('renders Japanese buttons and select placeholders',async()=>{const value=json(await settingsPanel(issue,{enabled:false,onboardingEnabled:false,template:'Gaming',startChannelId:null,revision:0,uiLanguage:'ja'},'ja'));expect(value).toContain('表示言語を選択');expect(value).toContain('NEXUS を有効化');});
 it('renders Japanese safe errors',async()=>{const value=json(await errorPanel(issue,'generic','ja','NXS-ABC123'));expect(value).toContain('処理結果を確認できませんでした');expect(value).toContain('エラー参照ID');});
 it('renders Japanese lifecycle stages',async()=>{const value=json(await lifecyclePanel(issue,metrics(),'ja'));for(const stage of ['参加','参加手続きを完了','最初の成功に到達','返信を受けた','その後も活動'])expect(value).toContain(`### ${stage}`);});
 it('renders Japanese experiment evidence',async()=>{const value=json(await experimentsPanel(issue,experiment('SUPPORTED'),'ja'));expect(value).toContain('現在の結果は改善を支持しています');expect(value).not.toContain('ランダム化実験');});
 it('keeps one main panel command and only direct self-service checks',()=>{const command=buildNexusCommand().toJSON(),status=command.options?.find(option=>option.name==='status');expect(command.description_localizations?.ja).toContain('コミュニティ');expect(status?.name_localizations?.ja).toBe('状態');expect(command.options?.map(option=>option.name)).toEqual(['panel','personalize','privacy','status']);});
 it('keeps English and Japanese copy complete and short in the control panel',async()=>{
  expect(Object.keys(ja).sort()).toEqual(Object.keys(en).sort());
  for(const key of Object.keys(en) as Array<keyof typeof en>){expect(en[key].trim(),key).not.toBe('');expect(ja[key].trim(),key).not.toBe('');}
  const banned=/\b(?:Activation|Retention|Cohort|Baseline|Journey|Lifecycle|Funnel|Intervention|Experiment|Friction|Maturity|Fallback|Hybrid)\b/i;
  for(const [key,value] of Object.entries(en))if(key.startsWith('control.')||key.startsWith('helper.'))expect(value,key).not.toMatch(banned);
  for(const locale of ['ja','en'] as const)for(const page of controlPages){const panel=await controlPanel(issue,page,{},locale);expect(panel.flags).toBe(32768);expect(panel.components?.length).toBeLessThanOrEqual(5);expect(json(panel)).not.toMatch(/undefined|\{(?:count|from|to)\}/);}
  const known=await errorPanel(issue,'permission','en');expect(json(known)).not.toContain('NXS-');expect(json(known)).toContain('Run Diagnostics');
 });
 it('keeps onboarding optional in guided setup',async()=>{const setup={required:false,recommendedMode:null,activationPreset:'reply',activationWindowDays:7,steps:[{key:'connect',complete:true,reason:'ready'},{key:'activation',complete:true,reason:'ready'},{key:'onboarding',complete:false,reason:'fallback_not_ready'},{key:'measuring',complete:false,reason:'measurement_waiting'}]} as Parameters<typeof guidedSetupPanel>[1];const value=json(await guidedSetupPanel(issue,setup));expect(value).toContain('optional');expect(value).toContain('View newcomers');expect(value).not.toContain('Configure onboarding');});
 it('observes Discord onboarding without changing it during first run',async()=>{const setup={required:true,recommendedMode:'native',nativeOnboardingEnabled:true,activationPreset:'not_configured',activationWindowDays:7,steps:[{key:'connect',complete:true,reason:'ready'},{key:'activation',complete:false,reason:'activation_missing'},{key:'onboarding',complete:true,reason:'ready'},{key:'measuring',complete:false,reason:'measurement_waiting'}]} as Parameters<typeof guidedSetupPanel>[1];const value=json(await guidedSetupPanel(issue,setup));expect(value).toContain('already in use');expect(value).toContain('without changing it');expect(value).toContain('Choose first success');});
 it('gives a direct channel permission fix and keeps the reference',async()=>{const value=json(await errorPanel(issue,'generic','en','NXS-ABC123','CHANNEL_PERMISSION_MISSING'));expect(value).toContain('Choose another channel');expect(value).toContain('View and Send permissions');expect(value).toContain('NXS-ABC123');expect(value).not.toContain('CHANNEL_PERMISSION_MISSING');});
 it('shows a plain improvement with one primary action',async()=>{const value=json(await improvePanel(issue,{id:'x',type:'CONNECTION_DROP',severity:'warning',stage:'connected',current:.52,previous:.66,difference:-.14,sampleSize:23,dataHealth:{status:'healthy',coverageRatio:1,label:'healthy',notes:[]},evidence:'observational',causality:'not_established',reason:'threshold_change',suggestedAction:'reply_rescue'}));expect(value).toContain('Improve this');expect(value).toContain('52%');expect(value).not.toContain('CONNECTION_DROP');});
 it('keeps generated panels within Discord component limits',async()=>{
  const panels=[await rootPanel(issue),await rootPanel(issue,'ja'),await rootPanel(issue,'bilingual'),await settingsPanel(issue,{enabled:false,onboardingEnabled:false,template:'Gaming',startChannelId:null,revision:0,uiLanguage:'bilingual'},'bilingual'),await overviewPanel(issue,metrics()),await overviewPanel(issue,metrics(),'ja'),await overviewPanel(issue,metrics(),'bilingual'),await lifecyclePanel(issue,metrics(),'ja'),await experimentsPanel(issue,experiment('SUPPORTED'),'bilingual')];
  const count=(value:unknown):number=>value&&typeof value==='object'&&'type' in value?1+('components' in value&&Array.isArray(value.components)?value.components.reduce((n:number,c:unknown)=>n+count(c),0):0):0;
  const inspect=(value:unknown)=>{if(!value||typeof value!=='object')return;const component=value as Record<string,unknown>;if(typeof component.label==='string')expect(component.label.length).toBeLessThanOrEqual(80);if(typeof component.placeholder==='string')expect(component.placeholder.length).toBeLessThanOrEqual(150);if(Array.isArray(component.options))for(const option of component.options as Array<{label:string;description?:string}>){expect(option.label.length).toBeLessThanOrEqual(100);if(option.description)expect(option.description.length).toBeLessThanOrEqual(100);}if(Array.isArray(component.components))component.components.forEach(inspect);};
  for(const panel of panels){expect(panel.flags).toBe(32768);expect(panel.allowed_mentions).toEqual({parse:[]});expect((panel.components??[]).reduce((n,c)=>n+count(c),0)).toBeLessThanOrEqual(40);inspect(panel);for(const component of panel.components??[])if(component.type===ComponentType.Container)expect(component.components.length).toBeLessThanOrEqual(40);}
 });
});
