import {describe,expect,it} from 'vitest';
import type {MetricResult} from '../../packages/analytics/src/registry.js';
import {compileActionTemplate,deliveryFunnel,retentionMaturity,toExperiment,toJourney,toKpi,toOpportunity,toTrendPoint} from '../../packages/presentation/src/index.js';

const metric=(key:MetricResult['metricKey'],value:number|null,numerator?:number,denominator?:number,options:{provisional?:boolean;coverage?:'healthy'|'degraded'|'incomplete'|'unavailable'}={}):MetricResult=>({metricKey:key,metricVersion:2,value,numerator,denominator,sampleSize:denominator??numerator??0,window:{from:'2026-01-01T00:00:00.000Z',to:'2026-01-31T00:00:00.000Z',asOf:'2026-02-01T00:00:00.000Z'},dataCoverage:{signal:'activity',expected:100,observed:options.coverage==='healthy'||!options.coverage?100:50,status:options.coverage??'healthy'},provisional:options.provisional??false});

describe('v0.3 presentation adapters',()=>{
 it('builds KPI comparisons without turning unavailable values into zero',()=>{const kpi=toKpi('activation_rate',metric('activation_rate',null,undefined,0,{coverage:'unavailable'}),metric('activation_rate',.4,8,20));expect(kpi).toMatchObject({current:null,previous:.4,delta:null,maturity:'unavailable'});});
 it('calculates funnel rates and previous-stage conversion from canonical numerators',()=>{const stages=toJourney({new_members:metric('new_members',100,100,100),onboarding_completion:metric('onboarding_completion',.8,80,100),activation_rate:metric('activation_rate',.5,50,100),direct_reply_connection_rate:metric('direct_reply_connection_rate',.3,30,100),d7_active_retention:metric('d7_active_retention',.2,20,100)});expect(stages.map(s=>[s.key,s.count,s.rateFromJoined,s.conversionFromPrevious])).toEqual([['joined',100,1,1],['onboarded',80,.8,.8],['first_value',50,.5,.625],['connected',30,.3,.6],['d7_active',20,.2,20/30]]);});
 it('preserves null trend values and maturity',()=>expect(toTrendPoint('2026-01-01',metric('activation_rate',null,undefined,0,{provisional:true}))).toMatchObject({value:null,maturity:'unavailable'}));
 it('keeps retention cohorts provisional until the full window matures',()=>{const start=Date.UTC(2026,0,1);expect(retentionMaturity(null,start,7,start+7*86400000)).toBe('provisional');expect(retentionMaturity(null,start,7,start+9*86400000)).toBe('unavailable');expect(retentionMaturity(.4,start,7,start+9*86400000)).toBe('mature');});
 it('translates deterministic diagnoses into non-causal opportunities',()=>{const result=toOpportunity({type:'CONNECTION_DROP',severity:'warning',cohort:'New members',facts:{metric:'direct_reply_connection_rate'},comparison:{current:.2,baseline:.4},sampleSize:40,confidenceLabel:'observational',causality:'not_established'},0,{direct_reply_connection_rate:metric('direct_reply_connection_rate',.2,8,40)});expect(result).toMatchObject({stage:'connected',difference:-.2,suggestedAction:'reply_rescue',causality:'not_established'});});
 it.each(['reply_rescue','welcome_helper','inactive_follow_up','channel_recommendation','event_recommendation'] as const)('compiles %s through the existing typed intervention schema',key=>{const result=compileActionTemplate(key,{channelId:'12345678901234567',eventId:'22345678901234567',recommendedChannelIds:['32345678901234567']});expect(result.name.length).toBeGreaterThan(0);expect(result.actions).toHaveLength(1);});
 it('never counts unknown delivery as delivered',()=>expect(deliveryFunnel(['delivered','unknown','failed','suppressed'])).toMatchObject({triggered:4,delivered:1,unknown:1,failed:1,suppressed:1}));
 it('translates experiment evidence and retains time-block spillover warnings',()=>{const result=toExperiment({id:'exp',publishedAt:'2026-01-01T00:00:00.000Z',definition:{name:'Welcome test',eligibility:[],randomization:'time_block',blockSeconds:86400,variants:[{key:'control',weight:50,interventionRevisionId:null},{key:'treatment',weight:50,interventionRevisionId:'123e4567-e89b-12d3-a456-426614174000'}],primaryMetric:'activation',windowSeconds:604800,minimumSample:20,guardrails:{maxLeaveRate:.3,maxFailureRate:.1,maxAlerts:100}}},{controlN:40,treatmentN:40,controlRate:.3,treatmentRate:.4,absoluteLift:.1,credibleInterval:[.01,.19],probabilityTreatmentBetter:.98,evidenceStatus:'SUPPORTED',assigned:90,mature:80,provisional:true,guardrails:{deliveryFailureRate:.02,alertVolume:38},dataCoverage:'healthy',coverageRatio:1,randomization:'time_block',state:'running'});expect(result).toMatchObject({evidence:'supported',absoluteLift:.1,deliveryHealth:{failureRate:.02},maturity:{assigned:90,mature:80}});expect(result.spilloverNote).toContain('spillover');expect(result.learning).not.toContain('INTENTION_TO_TREAT');});
});
